'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase,authRedirectUrl} from '../lib/supabase';
import Portal from '../portal';
import BusinessOnboarding from './business-onboarding';
import VerificationAdmin from './verification-admin';
export const one=value=>Array.isArray(value)?value[0]:value;
export async function rpc(name,args){const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data;}
export function problem(error,lang='es'){
 const es=lang==='es',m=error?.message||'',codes={INVALID_HOURS:['Revisa los días y tramos: inicio, final y pausas.','Check the days and intervals: opening, closing and breaks.'],HOURS_OVERLAP:['Los tramos del mismo día no pueden superponerse.','Intervals on the same day cannot overlap.'],WORKER_CONTACT_REQUIRED:['Cada integrante necesita nombre, correo y teléfono válidos.','Each member needs a valid name, email and phone.'],WORKER_ALREADY_IN_TEAM:['Ese correo ya está registrado en tu equipo.','That email is already registered in your team.'],WORKER_HAS_BOOKINGS:['Ese integrante tiene citas pendientes. Atiéndelas o cancélalas antes de retirarlo.','This member has pending appointments. Complete or cancel them before deactivating.'],FOREIGN_SERVICE:['Solo puedes asignar servicios de este comercio.','You can only assign services from this business.'],SLOT_UNAVAILABLE:['Ese horario acaba de ocuparse. Elige otro.','That time was just booked. Please choose another.'],BUSINESS_BASICS_REQUIRED:['Completa nombre, ubicación y horario de atención antes de enviar.','Add the name, location and opening hours before submitting.'],BUSINESS_OWNED:['Este negocio ya tiene propietario asignado.','This business already has an assigned owner.'],REQUEST_LOCKED:['La solicitud está en revisión y ya no puede editarse.','This request is under review and cannot be edited.'],ADMIN_REQUIRED:['Esta sección es exclusiva de administración.','This section is for administrators only.'],BLOCK_HAS_APPOINTMENT:['Ya hay una visita en ese horario. Reprograma o cancela primero.','A visit is already booked then. Reschedule or cancel it first.'],INVALID_TRANSITION:['Para aprobar, primero registra la visita realizada.','Record the completed visit before approving.'],CONTACT_REQUIRED:['Escribe tu nombre para coordinar la visita.','Enter your name to arrange the visit.'],AUTH_REQUIRED:['Inicia sesión para continuar.','Sign in to continue.'],CONFIRM_EMAIL:['Confirma tu correo antes de enviar.','Confirm your email before submitting.'],REQUEST_LIMIT:['Ya tienes cinco solicitudes abiertas.','You already have five open requests.']};
 const code=Object.keys(codes).find(k=>m.includes(k));return code?codes[code][es?0:1]:es?'No se pudo completar la acción. Intenta nuevamente.':'We could not complete that action. Please try again.';
}
export function AuthForm({lang,onClose}){
 const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false),es=lang==='es';
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const f=Object.fromEntries(new FormData(e.target));const result=signup?await supabase.auth.signUp({email:f.email,password:f.password,options:{emailRedirectTo:authRedirectUrl}}):await supabase.auth.signInWithPassword(f);if(result.error)throw result.error;if(result.data.session)onClose();else setSent(true);}catch{setError(es?'Revisa tus datos. Si ya tienes cuenta, usa Entrar.':'Check your details. If you already have an account, choose Sign in.');}finally{setBusy(false);}}
 return <section className="card intake-auth"><button className="quiet" onClick={onClose}>{es?'Cerrar':'Close'} ×</button><h2>{signup?(es?'Crea tu cuenta':'Create your account'):(es?'Entra con tu cuenta de Mi Espacio':'Sign in to Mi Espacio')}</h2><p>{es?'Puedes usar la misma cuenta con la que exploras la app.':'You can use the same account you use to explore the app.'}</p>{sent?<p role="status">{es?'Revisa tu correo para confirmar tu cuenta. Después podrás entrar.':'Check your email to confirm your account. Then sign in.'}</p>:<form onSubmit={submit}><label className="field"><span>Email</span><input name="email" type="email" autoComplete="email" required/></label><label className="field"><span>{es?'Contraseña':'Password'}</span><input name="password" type="password" minLength={6} autoComplete={signup?'new-password':'current-password'} required/></label><button disabled={busy} className="primary">{signup?(es?'Crear cuenta':'Create account'):(es?'Entrar':'Sign in')}</button></form>}{error&&<p role="alert">{error}</p>}<button className="text-button" onClick={()=>{setSignup(!signup);setSent(false);}}>{signup?(es?'Ya tengo cuenta':'I have an account'):(es?'Crear una cuenta':'Create an account')}</button></section>;
}
export default function BusinessAccess({admin=false}){
 const [session,setSession]=useState(null),[ready,setReady]=useState(false),[members,setMembers]=useState([]),[isAdmin,setIsAdmin]=useState(false),[lang,setLang]=useState('es'),[auth,setAuth]=useState(false),[failure,setFailure]=useState(false),[refresh,setRefresh]=useState(0),[add,setAdd]=useState(false);const authUser=useRef(null);
 useEffect(()=>{let alive=true;const receive=s=>{if(!alive)return;if(authUser.current!==s?.user.id){setReady(!s);authUser.current=s?.user.id;}if(!s)setReady(true);setSession(s);};supabase.auth.getSession().then(({data})=>receive(data.session));const {data}=supabase.auth.onAuthStateChange((event,s)=>receive(s));return()=>{alive=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{let alive=true;setMembers([]);setIsAdmin(false);setFailure(false);if(!session){return;}setReady(false);Promise.all([supabase.from('business_members').select('*').eq('user_id',session.user.id),supabase.from('platform_admins').select('user_id').eq('user_id',session.user.id)]).then(([m,a])=>{if(!alive)return;if(m.error||a.error)setFailure(true);else{setMembers(m.data);setIsAdmin(a.data.length>0);}setReady(true);});return()=>{alive=false;};},[session?.user.id,refresh]);
 if(!ready)return <div className="loading"><strong>me.</strong><p>{lang==='es'?'Cargando tu espacio…':'Loading your space…'}</p></div>;
 if(!admin&&session&&members.length&&!add)return <><div className="business-access-links"><a href="/">← Me.</a><button onClick={()=>setAdd(true)}>{lang==='es'?'Agregar otro negocio':'Add another business'}</button>{isAdmin&&<a href="/admin">{lang==='es'?'Administración':'Administration'} ↗</a>}</div><Portal initialSession={session} initialLang={lang} onLanguageChange={setLang} onLogout={()=>supabase.auth.signOut()}/></>;
 return <div className="shell pro intake-shell"><header className="intake-top"><a className="brand-mark" href="/">me.</a><strong>{admin?(lang==='es'?'ADMINISTRACIÓN':'ADMINISTRATION'):(lang==='es'?'TU NEGOCIO EN MI ESPACIO':'YOUR BUSINESS IN MI ESPACIO')}</strong><div className="language-toggle"><button onClick={()=>setLang('es')} className={lang==='es'?'chosen':''}>ES</button><button onClick={()=>setLang('en')} className={lang==='en'?'chosen':''}>EN</button></div>{session?<button className="quiet" onClick={()=>supabase.auth.signOut()}>{lang==='es'?'Salir':'Sign out'}</button>:<button className="quiet" onClick={()=>setAuth(true)}>{lang==='es'?'Entrar':'Sign in'}</button>}</header><main className="intake-main">{isAdmin&&!admin&&<a className="text-button" href="/admin">{lang==='es'?'Agenda de verificaciones':'Verification calendar'} ↗</a>}{members.length>0&&<button className="text-button" onClick={()=>setAdd(false)}>← {lang==='es'?'Volver a mi negocio':'Back to my business'}</button>}{auth&&<AuthForm lang={lang} onClose={()=>setAuth(false)}/>} {failure?<section className="card"><p role="alert">{lang==='es'?'No se pudo revisar tu acceso.':'Could not check your access.'}</p><button className="primary" onClick={()=>setRefresh(x=>x+1)}>{lang==='es'?'Reintentar':'Retry'}</button></section>:admin?(session&&isAdmin?<VerificationAdmin lang={lang}/>:<section className="card"><h1>{lang==='es'?'Administración general':'General administration'}</h1><p>{session?(lang==='es'?'Tu cuenta no tiene acceso a esta sección.':'Your account cannot access this section.'):(lang==='es'?'Entra con tu cuenta de administrador para llevar la agenda.':'Sign in with your administrator account to manage the calendar.')}</p>{!session&&<button className="primary" onClick={()=>setAuth(true)}>{lang==='es'?'Entrar':'Sign in'}</button>}</section>):<BusinessOnboarding session={session} lang={lang} onLogin={()=>setAuth(true)} onAssigned={()=>{setRefresh(x=>x+1);setAdd(false);}}/>}</main></div>;
}
