'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Image from 'next/image';
import {RatingMark,PublicFeedback,RateVisit} from './transaction-feedback';
import GalleryViewer from './gallery-viewer';
import ServiceBooking from './service-booking';
import VisitCheckout,{WalkInRegistration} from './visit-checkout';
import {pointsDisclaimer,pointsMoney} from './points-copy';
import {useLive,LiveBanner,LiveOffers,LiveCapsule,PromotionBooking} from './customer-live';
import Icon from './icons';
import {copy} from './customer-copy';
import {categoryIcons,localized,safeUrl,parentCategory,categoriesFor,distanceKm,rankBusinesses,filterBusinesses} from './discovery-model';
import {supabase,authRedirectUrl} from '../lib/supabase';
import '../customer.css';
const DEFAULT={locale:'es',appearance:'pro',live_enabled:false,display_name:'',interests:[],favorites:[],signals:{}};
function readGuest(){try{const s=JSON.parse(localStorage.getItem('mi-espacio-guest-v1'));return {...DEFAULT,locale:['es','en'].includes(s?.locale)?s.locale:'es',live_enabled:s?.live_enabled===true};}catch{return {...DEFAULT};}}
function mapsUrl(value){try{const u=new URL(value);if(u.protocol!=='https:')return null;return (u.hostname==='maps.app.goo.gl'||u.hostname==='maps.google.com'||(u.hostname==='goo.gl'&&u.pathname.startsWith('/maps/'))||(['google.com','www.google.com'].includes(u.hostname)&&u.pathname.startsWith('/maps')))?u.href:null;}catch{return null;}}
function PlaceImage({business,images,catalog,lang,priority=false}){const src=safeUrl(business.cover_image_url||images.find(x=>x.is_cover)?.image_url||images[0]?.image_url),[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);const parent=parentCategory(business,catalog);return <div className={'u-place-image tone-'+(parent?.slug||'spa-relajacion')}>{src&&!failed?<Image src={src} alt={localized(images[0],'alt',lang)||business.name} fill sizes="(max-width:600px) 85vw, 380px" unoptimized priority={priority} onError={()=>setFailed(true)}/>:<div className="u-place-art"><div className="u-art-orbit"/><Icon name={categoryIcons[parent?.slug]||'leaf'} size={68}/><span>{parent?localized(parent,'name',lang):'Mi Espacio'}</span></div>}</div>}
function Heading({title,subtitle,action}){return <div className="u-section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Empty({icon='search',title,description,action}){return <section className="u-empty"><span><Icon name={icon} size={33}/></span><h2>{title}</h2><p>{description}</p>{action}</section>}
export default function Customer({initialCatalog}){
 const [catalog,setCatalog]=useState(initialCatalog),[preview,setPreview]=useState(true),[prefs,setPrefs]=useState(DEFAULT),[session,setSession]=useState(null),[profileReady,setProfileReady]=useState(false),[screen,setScreen]=useState(0),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[city,setCity]=useState(''),[photoOnly,setPhotoOnly]=useState(false),[sort,setSort]=useState('recommended'),[geo,setGeo]=useState(null),[selected,setSelected]=useState(null),[detailTab,setDetailTab]=useState(0),[sheet,setSheet]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[visits,setVisits]=useState([]),[rewards,setRewards]=useState([]),[calendarTab,setCalendarTab]=useState(0),[visitTab,setVisitTab]=useState(0),[onboarding,setOnboarding]=useState(0),[draftInterests,setDraftInterests]=useState([]),[draftLive,setDraftLive]=useState(false),[catalogError,setCatalogError]=useState(false),[inbox,setInbox]=useState([]),[readNotices,setReadNotices]=useState([]),[inboxError,setInboxError]=useState(false),[liveFocus,setLiveFocus]=useState(null),[bookingService,setBookingService]=useState(null),[bookingPromotion,setBookingPromotion]=useState(null),[galleryIndex,setGalleryIndex]=useState(null),[walkIn,setWalkIn]=useState(null),[activeVisit,setActiveVisit]=useState(null),[wallet,setWallet]=useState(null),[ratingSummary,setRatingSummary]=useState([]);
 async function refreshRatings(){const {data,error}=await supabase.rpc('feedback_summary');if(!error)setRatingSummary(data||[]);}
 useEffect(()=>{refreshRatings();},[]);
 const lang=prefs.locale,t=copy[lang],dialogRef=useRef(null),toastTimer=useRef(null),inboxRequest=useRef(0),userId=session?.user.id;
 const categoryRows=catalog.categories.filter(c=>c.active!==false),parents=categoryRows.filter(c=>!c.parent_id),ranked=useMemo(()=>rankBusinesses(catalog,prefs.interests,prefs.favorites,prefs.signals),[catalog,prefs.interests,prefs.favorites,prefs.signals]);
 const homeCategories=['barberias','faciales','spa-relajacion','unas','fitness','salud','restaurantes','actividades-experiencias'].map(slug=>categoryRows.find(c=>c.slug===slug)).filter(Boolean);
 const homeIcons={barberias:'scissors',faciales:'beauty',unas:'nails',...categoryIcons};
 const filtered=useMemo(()=>filterBusinesses(ranked,catalog,{query,category,city,photoOnly,sort,location:geo}),[ranked,catalog,query,category,city,photoOnly,sort,geo]);
 const featured=(city?ranked.filter(b=>b.city===city):ranked).slice(0,6),related=ranked.filter(b=>b.match.reason==='affinity').slice(0,6),current=selected?catalog.businesses.find(b=>b.id===selected):null;
 const photoRows=current?catalog.gallery.filter(g=>g.business_id===current.id):[],offeringRows=current?catalog.offerings.filter(s=>s.business_id===current.id):[],serviceRows=current?catalog.services.filter(s=>s.business_id===current.id&&s.active):[],reviewRows=current?catalog.reviews.filter(r=>r.business_id===current.id):[];
 function notify(message){setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),5000);}
 async function action(fn){setBusy(true);try{await fn();}catch(e){notify(t.error);console.error('Mi Espacio action failed',e.message);}finally{setBusy(false);}}
 async function loadCatalog(){const {data:businesses,error}=await supabase.from('businesses').select('*').or('status.eq.published,and(status.eq.draft,directory_listed.eq.true)');if(error){setCatalogError(true);return;}setCatalogError(false);if(!businesses.length){setCatalog(initialCatalog);setPreview(true);return;}const ids=businesses.filter(b=>b.status==='published').map(b=>b.id),draftIds=new Set(businesses.filter(b=>b.status!=='published').map(b=>b.id));const tables={gallery:'business_gallery',offerings:'business_service_offerings',reviews:'business_reviews',services:'services',business_categories:'business_categories'};const results=await Promise.all(Object.entries(tables).map(async([key,table])=>{let rows=[];if(ids.length){let req=supabase.from(table).select('*').in('business_id',ids);if(['gallery','reviews'].includes(key))req=req.eq('status','published');const result=await req;if(result.error)throw result.error;rows=result.data;}return [key,[...rows,...(initialCatalog[key]||[]).filter(row=>draftIds.has(row.business_id))]];}));setCatalog({...initialCatalog,businesses,...Object.fromEntries(results)});setPreview(!businesses.some(b=>b.status==='published'));}
 useEffect(()=>{setPrefs(readGuest());loadCatalog().catch(()=>setCatalogError(true));const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setSheet('new-password');});return()=>{subscription.unsubscribe();clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 useEffect(()=>{if(!userId){setPrefs(readGuest());setProfileReady(true);setVisits([]);setRewards([]);setWallet(null);setActiveVisit(null);return;}setProfileReady(false);let disposed=false;async function load(){const results=await Promise.all([supabase.from('profiles').select('*').eq('user_id',userId).maybeSingle(),supabase.from('user_interests').select('*').eq('user_id',userId).order('slot'),supabase.from('favorites').select('*').eq('customer_id',userId),supabase.from('user_category_signals').select('*').eq('user_id',userId),supabase.from('visits').select('*').eq('customer_id',userId).order('starts_at',{ascending:false}),supabase.from('reward_ledger').select('*').eq('customer_id',userId)]);const error=results.find(r=>r.error)?.error;if(error)throw error;if(disposed)return;const [profile,interests,favs,signals,citas,ledger]=results.map(r=>r.data);setPrefs({...DEFAULT,...profile,display_name:profile?.display_name||session.user.user_metadata?.display_name||session.user.email?.split('@')[0]||'',interests:interests.map(i=>i.category_id),favorites:favs.map(f=>f.business_id),signals:Object.fromEntries(signals.filter(s=>s.signal==='view'||s.signal==='save').map(s=>[s.category_id,1]))});setVisits(citas);setRewards(ledger);setProfileReady(true);}load().catch(e=>{if(!disposed)notify(t.error);});return()=>{disposed=true;};},[userId]);
 async function loadInbox(){const request=++inboxRequest.current;if(!userId){setInbox([]);setReadNotices([]);return;}const [offers,verified,receipts,benefits,opportunities]=await Promise.all([supabase.from('promotions').select('*').eq('status','published'),supabase.from('customer_notifications').select('*').eq('customer_id',userId),supabase.from('notification_receipts').select('notification_key').eq('customer_id',userId),supabase.rpc('live_benefits'),supabase.rpc('reward_opportunities')]);if(request!==inboxRequest.current)return;if([offers,verified,receipts,benefits,opportunities].some(r=>r.error)){setInboxError(true);return;}const now=Date.now(),favorites=new Set(prefs.favorites);const items=(offers.data||[]).filter(p=>favorites.has(p.business_id)&&new Date(p.starts_at)<=now&&new Date(p.ends_at)>now&&(p.placement!=='live'||prefs.live_enabled)).map(p=>({...p,key:'promotion:'+p.id,kind:'promotion',body_es:p.description_es||p.description,body_en:p.description_en||p.description,expires_at:p.ends_at}));items.push(...(verified.data||[]).filter(n=>n.kind!=='reward_eligible'&&favorites.has(n.business_id)&&new Date(n.expires_at)>now).map(n=>({...n,key:'notice:'+n.id})));items.push(...(benefits.data||[]).filter(n=>prefs.live_enabled&&favorites.has(n.business_id)).map(n=>({...n,key:'benefit:'+n.id,body_es:n.description_es,body_en:n.description_en,created_at:n.starts_at,expires_at:n.ends_at})),...(opportunities.data||[]));setInbox(items.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)));setReadNotices((receipts.data||[]).map(r=>r.notification_key));setInboxError(false);}
 useEffect(()=>{let disposed=false;++inboxRequest.current;setInbox([]);setReadNotices([]);if(!userId){setInbox([]);setReadNotices([]);return;}if(profileReady)loadInbox();const refresh=()=>{if(!disposed&&document.visibilityState==='visible')loadInbox();};document.addEventListener('visibilitychange',refresh);const timer=setInterval(refresh,60000);return()=>{disposed=true;++inboxRequest.current;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[userId,profileReady,prefs.favorites,prefs.live_enabled]);
 async function openInbox(){if(!requireSession())return;setSheet('notifications');await loadInbox();}
 async function readNotice(n){await action(async()=>{if(!requireSession())return;if(!readNotices.includes(n.key)){const {error}=await supabase.from('notification_receipts').insert({customer_id:userId,notification_key:n.key});if(error&&error.code!=='23505')throw error;setReadNotices(prev=>[...prev,n.key]);}const b=catalog.businesses.find(b=>b.id===n.business_id);if(b){setSheet(null);openPlace(b);}});}
 const unreadCount=userId?inbox.filter(n=>!readNotices.includes(n.key)).length:0;
 function openLive(p,source){setLiveFocus(p?.id||null);setSheet('live');if(p?.id&&source)live.track(p,source).catch(()=>notify(t.error));}
 function reservePromotion(p){if(!requireSession())return;if(p.business?.requires_reservation===false){registerHere(p.business,catalog.services.find(s=>s.id===p.service_id),p);return;}setBookingService(null);setBookingPromotion(p);setSheet('booking');}
 function reserveService(s){if(!requireSession())return;if(current?.requires_reservation===false){registerHere(current,s);return;}setBookingPromotion(null);setBookingService(current?.status==='published'&&current.enrollment_status==='active'&&current.booking_enabled?s:null);setSheet('booking');}
 function booked(v){setVisits(prev=>[v,...prev.filter(x=>x.id!==v.id)]);setBookingPromotion(null);setBookingService(null);navigate(2);notify(lang==='es'?'Tu reserva está confirmada.':'Your booking is confirmed.');}
 useEffect(()=>{if(!userId)return;refreshConsumption().catch(()=>notify(t.error));},[userId]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')loadCatalog().catch(()=>setCatalogError(true));};const timer=setInterval(refresh,30000);return()=>clearInterval(timer);},[]);
 async function refreshConsumption(){const [v,r,w]=await Promise.all([supabase.from('visits').select('*').eq('customer_id',userId).order('starts_at',{ascending:false}),supabase.from('reward_ledger').select('*').eq('customer_id',userId),supabase.rpc('wallet_summary')]);if(v.error||r.error||w.error)throw v.error||r.error||w.error;setVisits(v.data||[]);setRewards(r.data||[]);setWallet(w.data);}
 function registerHere(b,service=null,promotion=null){if(!requireSession())return;setWalkIn({business:b,service,promotion});setSheet('walkin');}
 function registered(v){setVisits(prev=>[v,...prev.filter(x=>x.id!==v.id)]);setActiveVisit(v);setSheet('checkout');}
 function showVisit(v){if(!requireSession())return;setActiveVisit(v);setSheet('checkout');}
 const live=useLive({userId,enabled:prefs.live_enabled,ready:profileReady,catalog,home:screen===0,blocked:!!(sheet||selected||toast||galleryIndex!==null)});

 useEffect(()=>{const slug=new URLSearchParams(window.location.search).get('negocio');if(slug){const b=catalog.businesses.find(b=>b.slug===slug);if(b)setSelected(b.id);}const pop=()=>{setGalleryIndex(null);const slug=new URLSearchParams(window.location.search).get('negocio');setSelected(catalog.businesses.find(b=>b.slug===slug)?.id||null);};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[catalog]);
 useEffect(()=>{if(selected&&!sheet)document.querySelector('.u-detail-toolbar button')?.focus();},[selected,sheet]);
 useEffect(()=>{if(!sheet)return;const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=dialogRef.current;const first=dialog?.querySelector('button,input,select');first?.focus();const keyboard=e=>{if(e.key==='Escape')setSheet(null);if(e.key==='Tab'){const elements=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select,a[href]')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keyboard);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',keyboard);previous?.focus();};},[sheet]);
 function persistGuest(next){localStorage.setItem('mi-espacio-guest-v1',JSON.stringify(next));}
 function requireSession(){if(userId)return true;notify(t.sessionRequired);setSheet('auth');return false;}
 function directionsLink(b,primary=false){const url=mapsUrl(b.maps_url);if(!url)return null;const cls=primary?'u-primary':'u-text',label=t.directions+' · '+b.name;return userId?<a className={cls} href={url} target="_blank" rel="noreferrer" aria-label={label}><Icon name="pin" size={15}/>{t.directions}</a>:<button className={cls} aria-label={label} onClick={requireSession}><Icon name="pin" size={15}/>{t.directions}</button>;}
 async function changePrefs(patch){if(('appearance' in patch||'interests' in patch)&&!requireSession())return;const next={...prefs,...patch};if(userId){if(!profileReady)throw Error('Profile unavailable');const {error}=await supabase.from('profiles').upsert({user_id:userId,display_name:next.display_name||t.guest,locale:next.locale,appearance:next.appearance,live_enabled:next.live_enabled});if(error)throw error;}else persistGuest(next);setPrefs(next);}
 async function saveInterests(){if(!requireSession())return;await action(async()=>{if(userId){if(!profileReady)throw Error('Profile unavailable');const {error}=await supabase.rpc('set_interests',{p_categories:draftInterests});if(error)throw error;}await changePrefs({interests:draftInterests,live_enabled:draftLive});setSheet(null);notify(t.prefsSaved);});}
 function startPreferences(){if(!requireSession())return;setDraftInterests(prefs.interests);setDraftLive(prefs.live_enabled);setOnboarding(0);setSheet('preferences');}
 async function favorite(b){if(!requireSession())return;await action(async()=>{const exists=prefs.favorites.includes(b.id);const next={...prefs,favorites:exists?prefs.favorites.filter(id=>id!==b.id):[...prefs.favorites,b.id]};if(userId){const req=exists?supabase.from('favorites').delete().eq('customer_id',userId).eq('business_id',b.id):supabase.from('favorites').insert({customer_id:userId,business_id:b.id});const {error}=await req;if(error)throw error;}else persistGuest(next);setPrefs(next);notify(exists?t.removeSaved:t.saved);});}
 function recordView(b){const next={...prefs,signals:{...prefs.signals,[b.category_id]:Math.min(10,(prefs.signals[b.category_id]||0)+1)}};setPrefs(next);if(!userId)persistGuest(next);else if(profileReady)supabase.from('user_category_signals').upsert({user_id:userId,category_id:b.category_id,signal:'view',last_seen_at:new Date().toISOString()}).then(({error})=>{if(error)console.error('Signal not saved');});}
 function openPlace(b){recordView(b);setSelected(b.id);setDetailTab(0);const url=new URL(window.location.href);url.searchParams.set('negocio',b.slug);window.history.pushState({place:b.id},'',url);window.scrollTo(0,0);}
 function closePlace(){setGalleryIndex(null);setSelected(null);const url=new URL(window.location.href);url.searchParams.delete('negocio');window.history.replaceState({},'',url);window.scrollTo(0,0);}
 function navigate(n){if(n===2&&userId)refreshConsumption().catch(()=>notify(t.error));closePlace();setScreen(n);setSheet(null);window.scrollTo({top:0,behavior:'instant'});}
 function explore(cat=''){setCategory(cat);setQuery('');navigate(1);}
 function locate(){if(!navigator.geolocation){notify(t.geoDenied);return;}navigator.geolocation.getCurrentPosition(({coords})=>{setGeo({latitude:coords.latitude,longitude:coords.longitude});setSort('near');},()=>notify(t.geoDenied),{timeout:10000,maximumAge:300000});}
 async function auth(e,mode){e.preventDefault();const form=Object.fromEntries(new FormData(e.target));await action(async()=>{if(mode==='recover'){const {error}=await supabase.auth.resetPasswordForEmail(form.email,{redirectTo:authRedirectUrl});if(error)throw error;notify(t.recoverySent);return;}if(mode==='new-password'){const {error}=await supabase.auth.updateUser({password:form.password});if(error)throw error;setSheet(null);notify(t.passwordUpdated);return;}const response=mode==='signup'?await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:authRedirectUrl,data:{display_name:form.name}}}):await supabase.auth.signInWithPassword({email:form.email,password:form.password});if(response.error)throw response.error;if(mode==='signup'&&!response.data.session)notify(t.sent);else setSheet(null);});}
 async function share(b){const url=new URL('/',window.location.origin);url.searchParams.set('negocio',b.slug);try{if(navigator.share)await navigator.share({title:b.name,text:localized(b,'short_description',lang),url:url.href});else{await navigator.clipboard.writeText(url.href);notify(t.copied);}}catch(e){if(e.name!=='AbortError')notify(t.error);}}
 function card(b,compact=false){const images=catalog.gallery.filter(g=>g.business_id===b.id),parent=parentCategory(b,catalog),distance=distanceKm(b,geo);return <article key={b.id} className={'u-place-card'+(compact?' compact':'')}><div className="u-card-visual"><button className="u-image-button" aria-label={t.viewPlace+' · '+b.name} onClick={()=>openPlace(b)}><PlaceImage business={b} images={images} catalog={catalog} lang={lang}/></button><span className="u-photo-tag">{t.categoryNames[parent?.slug]||localized(parent,'name',lang)}</span><button className={'u-heart'+(prefs.favorites.includes(b.id)?' is-saved':'')} aria-label={(prefs.favorites.includes(b.id)?t.removeSaved:t.save)+' · '+b.name} disabled={busy} onClick={()=>favorite(b)}><Icon name="heart" size={19} filled={prefs.favorites.includes(b.id)}/></button></div><div className="u-card-content"><div className="u-card-category">{b.match?.reason&&<span><Icon name="spark" size={12}/>{t[{interest:'basedInterest',activity:'basedActivity',affinity:'basedAffinity'}[b.match.reason]]}</span>}<span>{b.status!=='published'?(lang==='es'?'Próximamente':'Coming soon'):b.listing_review_status==='approved'?t.verified:t.pending}</span></div><button className="u-title-button" onClick={()=>openPlace(b)}><h3>{b.name}</h3></button><RatingMark value={ratingSummary.find(r=>r.business_id===b.id)} lang={lang}/><p className="u-card-location"><Icon name="pin" size={13}/>{b.area||b.city}{distance!=null&&<span> · {distance.toFixed(1)} km</span>}</p>{!compact&&<p className="u-card-description">{localized(b,'short_description',lang)}</p>}<div className="u-card-footer"><button onClick={()=>openPlace(b)}>{t.viewPlace}<Icon name="arrow" size={16}/></button>{directionsLink(b)}</div></div></article>}
 const resultsGrid=rows=>rows.length?<div className="u-results-grid">{rows.map(b=>card(b))}</div>:<Empty title={t.empty} description={t.emptySearch} action={<button className="u-primary" onClick={()=>{setCategory('');setQuery('');setCity('');setPhotoOnly(false);}}>{t.clear}</button>}/>;
 const sheetTitle={'filters':t.filters,'location':t.location,'preferences':onboarding===0?t.prefsTitle:t.liveStep,'auth':t.signIn,'signup':t.signUp,'recover':t.forgot,'new-password':t.newPassword,'live':t.availableLive,'booking':bookingPromotion?(lang==='es'?'Agendar promoción':'Book promotion'):bookingService?(lang==='es'?'Agendar servicio':'Book service'):t.bookingSoon,'notifications':t.notifications,'walkin':lang==='es'?'Registrar mi visita':'Register my visit','checkout':lang==='es'?'Mi visita y mis puntos':'My visit & points'}[sheet];
 return <div className={'consumer theme-'+prefs.appearance+(screen===0?' u-home-screen':'')}>
 <header className="u-header" inert={!!(current||sheet||galleryIndex!==null)} aria-hidden={!!(current||sheet||galleryIndex!==null)}><a className="u-wordmark" href="/" aria-label="Mi Espacio"><span>me.</span><strong>Mi Espacio<small>{t.tagline}</small></strong></a><div className="u-header-actions"><button className="u-locale" aria-label={t.language} onClick={()=>action(()=>changePrefs({locale:lang==='es'?'en':'es'}))}>{lang.toUpperCase()}<Icon name="globe" size={14}/></button><button className="u-notification-button" aria-label={t.notifications+(unreadCount?' · '+unreadCount:'')} onClick={openInbox}><Icon name="bell" size={20}/>{unreadCount>0&&<span>{unreadCount>9?'9+':unreadCount}</span>}</button><button className="u-profile-icon" aria-label={t.nav[4]} onClick={()=>navigate(4)}><Icon name="user" size={20}/></button></div></header>
 {preview&&<button className="u-preview-strip" onClick={()=>notify(t.previewDetails)}><Icon name="shield" size={12}/>{t.preview}<Icon name="chevron" size={12}/></button>}
 <main className="u-main" inert={!!(current||sheet||galleryIndex!==null)} aria-hidden={!!(current||sheet||galleryIndex!==null)}>
 {screen===0&&<><div className="u-compact-hero"><div className="u-hero-topline"><span>{session&&prefs.display_name?(lang==='es'?'HOLA, ':'HELLO, ')+prefs.display_name.toUpperCase():(lang==='es'?'MI ESPACIO, TU MOMENTO':'MI ESPACIO, YOUR MOMENT')}</span><button className={'u-live-status'+(prefs.live_enabled?' enabled':'')} role="switch" aria-checked={prefs.live_enabled} aria-label={prefs.live_enabled?t.liveOn:t.liveOff} onClick={()=>action(()=>changePrefs({live_enabled:!prefs.live_enabled}))}><i/>{prefs.live_enabled?t.liveOn:t.liveOff}</button></div><div className="u-hero-copy"><div><h1>{t.welcome}</h1><p>{t.welcomeSub}</p></div><button className="u-hero-location" onClick={()=>setSheet('location')}><Icon name="pin" size={14}/><span>{city||t.allCabo}</span><Icon name="chevron" size={12}/></button></div></div><form className="u-search" onSubmit={e=>{e.preventDefault();navigate(1);}}><Icon name="search" size={21}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label={t.nav[1]}><Icon name="arrow" size={19}/></button></form><section className="u-category-section"><Heading title={t.categories}/><div className="u-category-scroll">{homeCategories.map(c=><button key={c.id} onClick={()=>explore(c.id)}><span className={'u-category-icon tone-'+c.slug}><Icon name={homeIcons[c.slug]} size={24}/></span><strong>{t.homeCategoryNames[c.slug]||t.categoryNames[c.slug]||localized(c,'name',lang)}</strong></button>)}</div></section>
 <section className="u-moment-banner"><Image className="u-wellness-photo" src="/images/wellness-coast.webp" alt={lang==='es'?'Escena costera ilustrativa de bienestar':'Illustrative coastal wellness scene'} fill sizes="(max-width:600px) 100vw, 1100px" unoptimized priority/><div><span>BIENESTAR · WELLNESS</span><h2>{lang==='es'?<>Bienestar<br/>cerca de ti.</>:<>Wellness<br/>close to you.</>}</h2><p>{lang==='es'?'Servicios, experiencias y más en Los Cabos.':'Services, experiences and more in Los Cabos.'}</p><button onClick={()=>explore()}>{lang==='es'?'Explorar ahora':'Explore now'}<Icon name="arrow" size={17}/></button></div><small className="u-photo-credit">{lang==='es'?'Imagen ilustrativa':'Illustrative image'}</small></section>
 <div className="u-home-content">
 <section className="u-home-places"><Heading title={t.forYou} subtitle={t.forYouSub} action={<button className="u-text" onClick={()=>explore()}>{t.seeAll}<Icon name="arrow" size={15}/></button>}/><div className="u-horizontal-cards">{featured.map(b=>card(b,true))}</div></section>
 {!prefs.interests.length&&<section className="u-personalize"><span className="u-personalize-icon"><Icon name="spark" size={24}/></span><div><h3>{t.personalize}</h3><p>{t.personalizeSub}</p><button onClick={startPreferences}>{t.choose}<Icon name="arrow" size={15}/></button></div></section>}
 {related.length>0&&<section className="u-home-places"><Heading title={t.related} subtitle={t.relatedSub}/><div className="u-horizontal-cards">{related.map(b=>card(b,true))}</div></section>}
 <LiveBanner live={live} enabled={prefs.live_enabled} t={t} lang={lang} catalog={catalog} onOpen={openLive} onEnable={()=>action(()=>changePrefs({live_enabled:true}))}/>
 </div></>}
 {screen===1&&<><div className="u-page-heading"><span>LOS CABOS</span><h1>{t.nav[1]}</h1><p>{t.forYouSub}</p></div><div className="u-explore-controls"><form className="u-search" onSubmit={e=>e.preventDefault()}><Icon name="search"/><input aria-label={t.searchExplore} placeholder={t.searchExplore} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label={t.clear} onClick={()=>setQuery('')}><Icon name="close" size={18}/></button>}<button type="button" className="u-filter-button" aria-label={t.filters} onClick={()=>setSheet('filters')}><Icon name="filter" size={20}/></button></form><div className="u-filter-chips"><button className={!category?'selected':''} onClick={()=>setCategory('')}>{t.all}</button>{parents.map(c=><button key={c.id} className={category===c.id?'selected':''} onClick={()=>setCategory(c.id)}>{t.categoryNames[c.slug]||localized(c,'name',lang)}</button>)}</div></div><div className="u-results-meta"><span>{filtered.length} {t.results}</span><button onClick={()=>setSheet('filters')}><Icon name="filter" size={14}/>{city||t[{recommended:'sortRecommended',name:'sortName',near:'sortNear'}[sort]]}</button></div>{resultsGrid(filtered)}</>}
 {screen===3&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.nav[3]}</h1><p>{t.favoritesSub}</p></div>{prefs.favorites.length?resultsGrid(ranked.filter(b=>prefs.favorites.includes(b.id))):<Empty icon="heart" title={t.emptyFavorites} description={t.emptyFavoritesSub} action={<button className="u-primary" onClick={()=>explore()}>{t.explore}<Icon name="arrow" size={17}/></button>}/>}</>}
 {screen===2&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.appointmentsTitle}</h1><p>{t.appointmentsSub}</p></div><div className="u-segments">{[t.appointments,t.rewards].map((label,n)=><button key={n} onClick={()=>setCalendarTab(n)} className={calendarTab===n?'selected':''}>{label}</button>)}</div>{calendarTab===0?<><div className="u-mini-tabs">{[t.upcoming,t.history].map((label,n)=><button className={visitTab===n?'selected':''} onClick={()=>setVisitTab(n)} key={n}>{label}</button>)}</div>{visits.filter(v=>visitTab===0?['scheduled','checked_in'].includes(v.status):!['scheduled','checked_in'].includes(v.status)).length?visits.filter(v=>visitTab===0?['scheduled','checked_in'].includes(v.status):!['scheduled','checked_in'].includes(v.status)).map(v=><article className="u-visit" key={v.id}><Icon name="calendar"/><div><strong>{catalog.businesses.find(b=>b.id===v.business_id)?.name||'Mi Espacio'}</strong><p>{v.starts_at&&new Date(v.starts_at).toLocaleString(lang==='es'?'es-MX':'en-US',{timeZone:'America/Mazatlan',dateStyle:'medium',timeStyle:'short'})}</p>{v.worker_name_snapshot&&<p>{localized(v,'service_name',lang)} · {v.worker_name_snapshot}</p>}<span>{t.status[v.status]}</span>{v.promotion_id&&<p className="u-promo-terms">{localized(v,'promotion_title',lang)} · {new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(v.booked_price_mxn)}</p>}{['scheduled','checked_in'].includes(v.status)&&<button className="u-text" onClick={()=>showVisit(v)}>{lang==='es'?'Mostrar código y revisar consumo':'Show code & review purchase'}</button>}{v.status==='completed'&&<RateVisit visit={v} lang={lang} onSaved={refreshRatings}/ >}{v.coverage_rate_snapshot!=null&&<p>{Math.round(v.coverage_rate_snapshot*100)}% · {lang==='es'?'Cobertura protegida con puntos':'Protected points coverage'}</p>}</div></article>):<Empty icon="calendar" title={t.noAppointments} description={t.noAppointmentsSub} action={<button className="u-primary" onClick={()=>explore()}>{t.explore}</button>}/>}</>:<><section className="u-reward-card"><Icon name="wallet" size={30}/><p>{t.collected}</p><strong>{new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(Number(wallet?.available_mxn||0))}</strong><span>MXN</span><small>{lang==='es'?'Saldo disponible para usar. Los puntos autorizados en consumos pendientes se apartan temporalmente.':'Available balance to use. Points authorized for pending purchases are temporarily held.'}</small></section>{rewards.length?rewards.map(r=><article className="u-visit" key={r.id}><Icon name="wallet"/><div><strong>{catalog.businesses.find(b=>b.id===r.business_id)?.name||'Mi Espacio'}</strong><p>+{r.credit_mxn} MXN</p></div></article>):<Empty icon="spark" title={t.noRewards} description={t.noRewardsSub}/>}</>}</>}
 {screen===4&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.profileTitle}</h1></div><section className="u-profile-card"><span className="u-large-avatar">{prefs.display_name?.charAt(0)?.toUpperCase()||<Icon name="user" size={32}/>}</span><h2>{prefs.display_name||t.guest}</h2><p>{session?session.user.email:t.guestDescription}</p>{!session&&<button className="u-primary" onClick={()=>setSheet('auth')}>{t.signIn}<Icon name="arrow" size={16}/></button>}</section><section className="u-account-note"><strong>{session?t.accountMode:t.guestMode}</strong><p>{session?t.accountScope:t.guestScope}</p></section><section className="u-settings-group"><div className="u-setting-title"><h2>{t.interests}</h2><button className="u-text" onClick={startPreferences}>{t.edit}<Icon name="chevron" size={15}/></button></div><div className="u-interest-labels">{prefs.interests.length?prefs.interests.map(id=><span key={id}>{localized(categoryRows.find(c=>c.id===id),'name',lang)}</span>):<button className="u-text" onClick={startPreferences}>{t.choose}<Icon name="arrow" size={15}/></button>}</div><div className="u-setting-row"><span className="u-setting-icon"><Icon name="live"/></span><div><strong>Mi Espacio Live</strong><p>{t.liveHelp}</p></div><button className={'u-switch'+(prefs.live_enabled?' on':'')} role="switch" aria-checked={prefs.live_enabled} aria-label="Mi Espacio Live" disabled={busy} onClick={()=>action(()=>changePrefs({live_enabled:!prefs.live_enabled}))}><span>{prefs.live_enabled?t.liveOn:t.liveOff}</span><i/></button></div><div className="u-setting-row"><span className="u-setting-icon"><Icon name="globe"/></span><div><strong>{t.language}</strong></div><div className="u-language-options"><button disabled={busy} className={lang==='es'?'selected':''} onClick={()=>action(()=>changePrefs({locale:'es'}))}>ES</button><button disabled={busy} className={lang==='en'?'selected':''} onClick={()=>action(()=>changePrefs({locale:'en'}))}>EN</button></div></div></section><section className="u-settings-group"><h2>{t.appearance}</h2><div className="u-palette-options">{[['pro','Navy'],['modern_teal','Modern Teal'],['warm_neutral','Warm Neutral']].map(([p,label])=><button key={p} disabled={busy} aria-pressed={prefs.appearance===p} className={prefs.appearance===p?'selected':''} onClick={()=>action(()=>changePrefs({appearance:p}))}><span className={'u-palette-swatch '+p}/><strong>{label}</strong>{prefs.appearance===p&&<Icon name="check" size={16}/>}</button>)}</div></section><a className="u-commerce-link" href="/comercio"><div><strong>{t.commerce}</strong><span>{t.commerceLink}</span></div><Icon name="arrow"/></a>{session?<button className="u-sign-out" onClick={()=>action(async()=>{const {error}=await supabase.auth.signOut();if(error)throw error;})}><Icon name="logout" size={18}/>{t.signOut}</button>:<button className="u-reset" onClick={()=>{localStorage.removeItem('mi-espacio-guest-v1');setPrefs({...DEFAULT});notify(t.prefsSaved);}}>{t.resetPreview}</button>}</>}
 {catalogError&&<button className="u-retry" onClick={()=>loadCatalog().catch(()=>notify(t.error))}>{t.retry}<Icon name="arrow" size={13}/></button>}
 <div className="u-bottom-signature"><span>me.</span><p>{t.tagline}</p></div>
 </main>
 <nav className="u-bottom-nav" inert={!!(current||sheet||galleryIndex!==null)} aria-hidden={!!(current||sheet||galleryIndex!==null)} aria-label={lang==='es'?'Navegación principal':'Main navigation'}>{t.nav.map((label,n)=><button key={n} className={screen===n?'selected':''} aria-current={screen===n?'page':undefined} onClick={()=>navigate(n)}><span><Icon name={['home','search','calendar','heart','user'][n]} size={22}/>{n===3&&prefs.favorites.length>0&&<i>{prefs.favorites.length}</i>}</span><strong>{label}</strong></button>)}</nav>
 {current&&<div className="u-detail-view" role="dialog" aria-modal="true" aria-label={current.name} inert={!!(sheet||galleryIndex!==null)} aria-hidden={!!(sheet||galleryIndex!==null)}><div className="u-detail-content"><header className="u-detail-toolbar"><button className="u-round-button" aria-label={t.back} onClick={closePlace}><Icon name="back"/></button><strong>{current.name}</strong><button className="u-round-button" aria-label={t.share} onClick={()=>share(current)}><Icon name="share" size={19}/></button><button className={'u-round-button'+(prefs.favorites.includes(current.id)?' is-saved':'')} aria-label={(prefs.favorites.includes(current.id)?t.removeSaved:t.save)+' · '+current.name} disabled={busy} onClick={()=>favorite(current)}><Icon name="heart" size={19} filled={prefs.favorites.includes(current.id)}/></button></header><div className="u-detail-hero"><PlaceImage business={current} images={photoRows} catalog={catalog} lang={lang} priority/><span>{photoRows.length?photoRows.length+' '+t.photos:t.photoPending}</span></div><div className="u-detail-intro"><span className="u-detail-category">{t.categoryNames[parentCategory(current,catalog)?.slug]} · {current.city}</span><h1>{current.name}</h1><p>{localized(current,'short_description',lang)}</p><div className="u-detail-status"><Icon name="shield" size={15}/>{current.listing_review_status==='approved'?t.verified:t.pending}</div></div><div className="u-detail-tabs">{[t.about,t.services,t.photos,t.reviews].map((label,n)=><button key={n} className={detailTab===n?'selected':''} onClick={()=>setDetailTab(n)}>{label}</button>)}</div><div className="u-detail-body">
 {detailTab===0&&<><section><h2>{t.about}</h2><p>{localized(current,'description',lang)}</p></section><section><h2>{t.address}</h2><div className="u-address-card"><Icon name="pin" size={23}/><div><strong>{current.address||current.city}</strong><p>{localized(current,'directions',lang)}</p>{directionsLink(current)}</div></div></section>{localized(current,'opening_hours',lang)&&<section><h2>{t.hours}</h2><div className="u-hours"><Icon name="clock"/><p>{localized(current,'opening_hours',lang)}</p></div></section>}{current.enrollment_status==='active'&&<div className="u-benefit"><Icon name="spark"/><div><strong>{Math.round(current.reward_rate*100)}% · {t.rewardRate}</strong><p>{t.rewardsInfo}</p></div></div>}</>}
 {current.status==='published'&&current.enrollment_status==='active'&&<section className="u-business-benefit"><strong>{lang==='es'?'Hasta ':'Up to '}{Math.round(Number(current.points_coverage_rate??.5)*100)}% {lang==='es'?'con puntos elegibles':'with eligible points'}</strong><p>{pointsDisclaimer(lang)}</p><button className="u-primary" onClick={()=>registerHere(current)}>{lang==='es'?'Ya estoy aquí · usar Me.':'I’m here · use Me.'}</button><small>{lang==='es'?'Acumula o redime tras verificar tu visita y confirmar tu consumo.':'Earn or redeem after verifying your visit and confirming your purchase.'}</small></section>}
 {detailTab===1&&<><h2>{t.services}</h2>{serviceRows.length?serviceRows.map(s=><article className="u-service-row" key={s.id}><div><h3>{localized(s,'name',lang)}</h3><p>{localized(s,'description',lang)}</p><span><Icon name="clock" size={13}/>{s.duration_minutes} min · {new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(s.price_mxn)}</span></div><button aria-label={t.ask+' · '+localized(s,'name',lang)} onClick={()=>reserveService(s)}><Icon name="chevron" size={19}/></button></article>):offeringRows.map(s=><article className="u-service-row" key={s.id}><div><h3>{localized(s,'title',lang)}</h3><p>{localized(s,'description',lang)}</p><span>{t.price} / {t.duration}: {t.confirming}</span></div><span className="u-service-pending"><Icon name="clock" size={17}/></span></article>)}{!serviceRows.length&&!offeringRows.length&&<Empty icon="leaf" title={t.confirming} description={t.bookingInfo}/>}<p className="u-detail-note">{t.bookingInfo}</p></>}
 {detailTab===2&&<><h2>{t.photos}</h2>{photoRows.length?<div className="u-gallery-grid">{photoRows.map((p,index)=><figure key={p.id}><button className="u-gallery-open" aria-label={(lang==='es'?'Abrir foto ':'Open photo ')+(index+1)+' · '+current.name} onClick={()=>setGalleryIndex(index)}><PlaceImage business={{...current,cover_image_url:p.image_url}} images={[p]} catalog={catalog} lang={lang}/><span className="u-gallery-expand"><Icon name="image" size={15}/>{lang==='es'?'Ver foto':'View photo'}</span></button><figcaption>{localized(p,'caption',lang)}</figcaption></figure>)}</div>:<Empty icon="image" title={t.photoPending} description={t.researchNotice}/>}</>}
 {detailTab===3&&<><h2>{t.reviews}</h2><PublicFeedback businessId={current.id} lang={lang} value={ratingSummary.find(r=>r.business_id===current.id)}/>{reviewRows.map(r=><article className="u-review" key={r.id}><span>{r.kind==='editorial'?t.editorial:t.researchNote}</span><p>{localized(r,'body',lang)}</p>{r.source_label&&<span>{r.source_label}</span>}</article>)}</>}
 {preview&&<p className="u-research-notice"><Icon name="shield" size={16}/>{t.researchNotice}</p>}
 </div></div><div className="u-detail-actions">{directionsLink(current,true)}<button className="u-secondary" onClick={()=>{if(current.requires_reservation===false&&current.status==='published'&&current.enrollment_status==='active'){registerHere(current);return;}if(serviceRows.length&&current.booking_enabled){setDetailTab(1);}else{setBookingService(null);setBookingPromotion(null);setSheet('booking');}}}><Icon name="calendar" size={18}/>{current.requires_reservation===false&&current.status==='published'&&current.enrollment_status==='active'?(lang==='es'?'Registrar mi visita':'Register my visit'):serviceRows.length&&current.booking_enabled?(lang==='es'?'Elegir servicio':'Choose service'):t.bookingSoon}</button></div></div>}
 {sheet&&<div className="u-sheet-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSheet(null);}}><section ref={dialogRef} className={'u-sheet '+(sheet==='preferences'?'u-onboarding':'')} role="dialog" aria-modal="true" aria-labelledby="sheet-title"><header className="u-sheet-header"><div className="u-sheet-handle"/><div><h2 id="sheet-title">{sheetTitle}</h2><button aria-label={t.close} className="u-round-button" onClick={()=>setSheet(null)}><Icon name="close" size={21}/></button></div></header><div className="u-sheet-body">
 {['filters','location'].includes(sheet)&&<><label className="u-field"><span>{t.city}</span><select aria-label={t.city} value={city} onChange={e=>setCity(e.target.value)}><option value="">{t.allCities}</option>{[...new Set(catalog.businesses.map(b=>b.city))].filter(Boolean).map(c=><option key={c}>{c}</option>)}</select></label>{sheet==='filters'&&<><label className="u-field"><span>{t.category}</span><select aria-label={t.category} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{categoryRows.map(c=><option key={c.id} value={c.id}>{localized(c,'name',lang)}</option>)}</select></label><label className="u-field"><span>{t.sort}</span><select aria-label={t.sort} value={sort} onChange={e=>{setSort(e.target.value);if(e.target.value==='near'&&!geo)locate();}}><option value="recommended">{t.sortRecommended}</option><option value="name">{t.sortName}</option><option value="near">{t.sortNear}</option></select></label><label className="u-checkbox"><input type="checkbox" checked={photoOnly} onChange={e=>setPhotoOnly(e.target.checked)}/>{t.photoOnly}</label></>}<button className="u-location-button" onClick={locate}><Icon name="pin" size={18}/>{t.nearMe}</button><button className="u-primary u-full" onClick={()=>{setSheet(null);if(sheet==='filters')setScreen(1);}}>{t.apply}<Icon name="arrow" size={17}/></button></>}
 {sheet==='preferences'&&(onboarding===0?<><p className="u-overline">{t.stepOne}</p><p>{t.prefsSub}</p><div className="u-interest-counter">{draftInterests.length} / 5 {t.selected}</div><div className="u-interest-grid">{categoryRows.filter(c=>c.parent_id).map(c=>{const checked=draftInterests.includes(c.id),parent=categoryRows.find(p=>p.id===c.parent_id);return <button key={c.id} className={checked?'selected':''} aria-pressed={checked} disabled={!checked&&draftInterests.length>=5} onClick={()=>setDraftInterests(checked?draftInterests.filter(id=>id!==c.id):[...draftInterests,c.id])}><Icon name={categoryIcons[parent?.slug]} size={20}/><span>{localized(c,'name',lang)}</span>{checked&&<Icon name="check" size={16}/>}</button>})}</div><button disabled={draftInterests.length<1||draftInterests.length>5} className="u-primary u-full" onClick={()=>setOnboarding(1)}>{t.next}<Icon name="arrow" size={18}/></button><button className="u-skip" onClick={()=>setSheet(null)}>{t.skip}</button></>:<><p className="u-overline">{t.stepTwo}</p><div className="u-onboard-guide">{[['live','Live',lang==='es'?'Actívalo para recibir oportunidades y promociones mientras exploras. Tú decides cuándo.':'Turn it on for opportunities and promotions as you explore. You are in control.'],['heart',lang==='es'?'Favoritos':'Favorites',lang==='es'?'Guarda los lugares que te gustan y encuentra sus novedades fácilmente.':'Save places you love and easily find their updates.'],['sparkles',lang==='es'?'Quizás también te gusten':'You might also like',lang==='es'?'Descubre lugares afines a tus gustos, aunque no los hayas elegido aquí.':'Discover places related to your tastes, even beyond these interests.']].map(([icon,title,body])=><article key={icon}><Icon name={icon} size={26}/><div><strong>{title}</strong><p>{body}</p></div></article>)}</div><p>{t.liveStepSub}</p><button className={'u-choice'+(draftLive?' selected':'')} aria-pressed={draftLive} onClick={()=>setDraftLive(true)}><Icon name="live"/><strong>{t.liveYes}</strong>{draftLive&&<Icon name="check" size={17}/>}</button><button className={'u-choice'+(!draftLive?' selected':'')} aria-pressed={!draftLive} onClick={()=>setDraftLive(false)}><Icon name="leaf"/><strong>{t.liveNo}</strong>{!draftLive&&<Icon name="check" size={17}/>}</button><button className="u-primary u-full" disabled={busy} onClick={saveInterests}>{t.finish}<Icon name="arrow" size={17}/></button><button className="u-skip" onClick={()=>setOnboarding(0)}>{t.back}</button></>)}
 {['auth','signup','recover','new-password'].includes(sheet)&&<form onSubmit={e=>auth(e,sheet)}>{sheet==='signup'&&<label className="u-field"><span>{t.name}</span><input name="name" autoComplete="name" required/></label>}{sheet!=='new-password'&&<label className="u-field"><span>{t.email}</span><input name="email" type="email" autoComplete="email" required/></label>}{sheet!=='recover'&&<label className="u-field"><span>{sheet==='new-password'?t.newPassword:t.password}</span><input name="password" type="password" autoComplete={sheet==='auth'?'current-password':'new-password'} minLength={6} required/></label>}<button disabled={busy} className="u-primary u-full">{sheet==='recover'?t.forgot:sheet==='signup'?t.signUp:sheet==='new-password'?t.updatePassword:t.enter}<Icon name="arrow" size={17}/></button>{sheet==='auth'&&<><button type="button" className="u-skip" onClick={()=>setSheet('recover')}>{t.forgot}</button><button type="button" className="u-secondary u-full" onClick={()=>setSheet('signup')}>{t.signUp}</button></>}{sheet==='signup'&&<button type="button" className="u-skip" onClick={()=>setSheet('auth')}>{t.signIn}</button>}</form>}
 {sheet==='live'&&(!userId?<Empty icon="live" title={t.availableLive} description={t.liveLogin} action={<button className="u-primary" onClick={()=>setSheet('auth')}>{t.signIn}</button>}/>:!prefs.live_enabled?<Empty icon="live" title={t.liveDisabled} description={t.liveDescription} action={<button className="u-primary" onClick={()=>action(()=>changePrefs({live_enabled:true}))}>{t.activate}</button>}/>:live.offers.length||live.loading||live.error?<LiveOffers live={live} t={t} lang={lang} catalog={catalog} focused={liveFocus} onReserve={reservePromotion} onPlace={b=>{setSheet(null);openPlace(b);}}/>:<Empty icon="live" title={t.noLive} description={t.noLiveSub} action={<button className="u-primary" onClick={()=>{setSheet(null);explore();}}>{t.explore}</button>}/>)}
 {sheet==='notifications'&&(inboxError?<Empty icon="bell" title={t.error} description={t.inboxRetry} action={<button className="u-primary" onClick={loadInbox}>{t.retry}</button>}/>:inbox.length?<div className="u-notification-list">{inbox.map(n=><button key={n.key} className={'u-notification-item'+(!readNotices.includes(n.key)?' unread':'')} disabled={busy} onClick={()=>readNotice(n)}><span className="u-notification-symbol"><Icon name={n.kind==='reward_eligible'?'wallet':'bell'} size={22}/></span><div><span className="u-notification-kind">{n.kind==='reward_eligible'?t.rewardNotice:t.promotionNotice}</span><h3>{localized(n,'title',lang)}</h3><p>{localized(n,'body',lang)}</p><small>{catalog.businesses.find(b=>b.id===n.business_id)?.name} · {new Date(n.created_at).toLocaleDateString(lang==='es'?'es-MX':'en-US')}</small></div>{!readNotices.includes(n.key)&&<i/>}</button>)}</div>:<Empty icon="bell" title={t.noNotifications} description={t.notificationsHelp}/>)}
 {sheet==='walkin'&&walkIn&&<WalkInRegistration key={walkIn.business.id+':'+(walkIn.service?.id||'')+':'+(walkIn.promotion?.id||'')} {...walkIn} live={live} lang={lang} onRegistered={registered}/>}
 {sheet==='checkout'&&activeVisit&&<VisitCheckout key={activeVisit.id} visitId={activeVisit.id} business={catalog.businesses.find(b=>b.id===activeVisit.business_id)||walkIn?.business||{id:activeVisit.business_id,name:'Me.'}} lang={lang} onChanged={()=>refreshConsumption().catch(()=>notify(t.error))}/>}
 {sheet==='booking'&&(bookingPromotion?<PromotionBooking key={bookingPromotion.id} promotion={bookingPromotion} live={live} catalog={catalog} lang={lang} t={t} onBooked={booked}/>:bookingService&&current?<ServiceBooking key={bookingService.id} service={bookingService} business={current} lang={lang} t={t} onBooked={booked}/>:<Empty icon="calendar" title={t.bookingSoon} description={t.bookingInfo}/>)}
 </div></section></div>}
 {galleryIndex!==null&&current&&photoRows.length>0&&<GalleryViewer photos={photoRows} initialIndex={galleryIndex} businessName={current.name} lang={lang} onClose={()=>setGalleryIndex(null)}/>}
 <LiveCapsule live={live} t={t} lang={lang} catalog={catalog} onOpen={openLive}/>
 {toast&&<div className="u-toast" role="status"><Icon name="check" size={17}/><span>{toast}</span><button aria-label={t.close} onClick={()=>setToast('')}><Icon name="close" size={15}/></button></div>}
 </div>;
}
