'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Image from 'next/image';
import Icon from './icons';
import {supabase} from '../lib/supabase';
import {localized,safeUrl,parentCategory,categoryIcons} from './discovery-model';
const valid=p=>p.status==='published'&&new Date(p.starts_at)<=Date.now()&&new Date(p.ends_at)>Date.now();
export function useLive({userId,enabled,ready,catalog,home,blocked}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(false),[index,setIndex]=useState(0),[capsule,setCapsule]=useState(null),[visible,setVisible]=useState(true);
 const seen=useRef(new Set()),request=useRef(0),clicks=useRef(new Map());
 const offers=useMemo(()=>rows.filter(valid).map(p=>({...p,business:catalog.businesses.find(b=>b.id===p.business_id)})).filter(p=>p.business?.status==='published'),[rows,catalog]);
 async function refresh(){const token=++request.current;if(!userId||!enabled||!ready)return;setLoading(true);try{const result=await supabase.from('promotions').select('*').eq('placement','live').eq('status','published');if(token!==request.current)return;if(result.error)throw result.error;setRows(result.data||[]);setError(false);}catch{if(token===request.current){setRows([]);setError(true);}}finally{if(token===request.current)setLoading(false);}}
 useEffect(()=>{try{seen.current=new Set(JSON.parse(sessionStorage.getItem('me-live-batch:'+userId)||'[]'));}catch{seen.current=new Set();}clicks.current.clear();setCapsule(null);},[userId]);
 useEffect(()=>{if(!userId||!enabled||!ready){++request.current;setRows([]);setLoading(false);setError(false);setCapsule(null);return;}refresh();const onVisibility=()=>{setVisible(document.visibilityState==='visible');if(document.visibilityState==='visible')refresh();};const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh();},30000);document.addEventListener('visibilitychange',onVisibility);return()=>{++request.current;clearInterval(timer);document.removeEventListener('visibilitychange',onVisibility);};},[userId,enabled,ready]);
 useEffect(()=>{const ends=rows.filter(valid).map(p=>new Date(p.ends_at).getTime());if(!ends.length)return;const timer=setTimeout(()=>setRows(prev=>prev.filter(valid)),Math.min(2147483647,Math.max(0,Math.min(...ends)-Date.now()+20)));return()=>clearTimeout(timer);},[rows]);
 const ids=offers.map(p=>p.id).join('|');
 useEffect(()=>{if(!home||!enabled||!visible||blocked||!offers.length)return;const pick=()=>setIndex(prev=>offers.length<2?0:(prev+1+Math.floor(Math.random()*(offers.length-1)))%offers.length);pick();const timer=setInterval(pick,6000);return()=>clearInterval(timer);},[home,enabled,visible,blocked,ids]);
 useEffect(()=>{if(!enabled||blocked||!visible||!home){setCapsule(null);return;}if(capsule||seen.current.size>=5)return;const pending=offers.filter(p=>!seen.current.has(p.id));const offer=pending[Math.floor(Math.random()*pending.length)];if(!offer)return;const timer=setTimeout(()=>{if(!valid(offer))return;seen.current.add(offer.id);try{sessionStorage.setItem('me-live-batch:'+userId,JSON.stringify([...seen.current]));}catch{}setCapsule(offer);},3000+Math.floor(Math.random()*4001));return()=>clearTimeout(timer);},[enabled,blocked,visible,home,ids,capsule?.id,userId]);
 useEffect(()=>{if(!capsule)return;const timer=setTimeout(()=>setCapsule(null),4000);return()=>clearTimeout(timer);},[capsule]);
 async function track(p,source){const event=crypto.randomUUID();const pending=supabase.rpc('record_promotion_click',{p_promotion:p.id,p_event:event,p_source:source}).then(({data,error})=>{if(error)throw error;return data;});clicks.current.set(p.id,pending);try{return await pending;}catch(e){if(clicks.current.get(p.id)===pending)clicks.current.delete(p.id);throw e;}}
 async function attribution(p){return clicks.current.get(p.id)||track(p,'service_cta');}
 return {track,attribution,clearAttribution:p=>clicks.current.delete(p.id),offers,loading,error,refresh,offer:offers[index%offers.length]||null,capsule:enabled&&capsule&&valid(capsule)&&!blocked?capsule:null,dismiss:()=>setCapsule(null)};
}
function LivePhoto({offer,catalog,lang}){
 const images=catalog.gallery.filter(g=>g.business_id===offer.business_id),src=safeUrl(offer.images?.[0]?.url||offer.image_url||offer.business.cover_image_url||images.find(g=>g.is_cover)?.image_url||images[0]?.image_url),[failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[src]);const category=parentCategory(offer.business,catalog);
 return src&&!failed?<Image src={src} alt={localized(offer,'title',lang)+' · '+offer.business.name} fill sizes="(max-width:600px) 90vw, 600px" unoptimized onError={()=>setFailed(true)}/>:<div className="u-live-art"><Icon name={categoryIcons[category?.slug]||'leaf'} size={38}/></div>;
}
export function LiveBanner({live,enabled,t,lang,catalog,onOpen,onEnable}){
 if(enabled&&live.offer)return <section className="u-live-photo-banner" data-offer={live.offer.id}><LivePhoto offer={live.offer} catalog={catalog} lang={lang}/><div className="u-live-photo-copy"><span><i className="u-live-pulse"/> MI ESPACIO LIVE</span><h3>{t.liveInvite}</h3><p>{live.offer.business.name} · {localized(live.offer,'title',lang)}</p><button onClick={()=>onOpen(live.offer,'home_card')}>{t.availableLive}<Icon name="arrow" size={16}/></button></div></section>;
 return <section className={'u-live-banner'+(enabled?' enabled':'')}><Icon name="live" size={30}/><div><span>MI ESPACIO LIVE</span><h3>{enabled?t.liveActiveTitle:t.liveTitle}</h3><p>{enabled?(live.loading?t.liveLoading:live.error?t.liveRetry:t.liveActiveSub):t.liveDescription}</p><button onClick={enabled?()=>onOpen():onEnable}>{enabled?t.availableLive:t.activate}<Icon name="arrow" size={16}/></button></div></section>;
}
function PromotionGallery({offer,catalog,lang}){const [index,setIndex]=useState(0);const images=offer.images||[];return <div className="u-live-offer-photo"><LivePhoto offer={{...offer,images:images.length?[images[index%images.length]]:[]}} catalog={catalog} lang={lang}/>{images.length>1&&<div className="u-promo-gallery-controls"><button aria-label={lang==='es'?'Foto anterior':'Previous photo'} onClick={()=>setIndex(i=>(i-1+images.length)%images.length)}>‹</button><span>{index%images.length+1} / {images.length}</span><button aria-label={lang==='es'?'Siguiente foto':'Next photo'} onClick={()=>setIndex(i=>(i+1)%images.length)}>›</button></div>}</div>;}
export function LiveOffers({live,t,lang,catalog,onPlace,onReserve,focused}){
 if(live.loading&&!live.offers.length)return <p className="u-live-empty" role="status">{t.liveLoading}</p>;
 if(live.error)return <div className="u-live-empty"><p>{t.liveRetry}</p><button className="u-primary" onClick={live.refresh}>{t.retry}</button></div>;
 const sorted=[...live.offers].sort((a,b)=>Number(b.id===focused)-Number(a.id===focused));
 return sorted.map(p=><article className={'u-live-offer'+(p.id===focused?' focused':'')} key={p.id} data-promotion={p.id}><PromotionGallery offer={p} catalog={catalog} lang={lang}/><span>LIVE · {p.business.name}</span><h3>{localized(p,'title',lang)}</h3><p>{localized(p,'description',lang)}</p>{p.special_price_mxn!=null&&<strong className="u-promo-price">{new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(p.special_price_mxn)}</strong>}<small>{lang==='es'?'Válida hasta: ':'Valid until: '}{new Date(p.ends_at).toLocaleString(lang==='es'?'es-MX':'en-US',{timeZone:p.business.timezone||'America/Mazatlan'})}</small>{localized(p,'terms',lang)&&<p className="u-promo-terms">{localized(p,'terms',lang)}</p>}<button className="u-primary" onClick={()=>onReserve(p)}>{lang==='es'?'Agendar esta promoción':'Book this promotion'}<Icon name="calendar" size={16}/></button><button className="u-text" onClick={()=>onPlace(p.business)}>{t.viewPlace}<Icon name="arrow" size={16}/></button></article>);
}
export function PromotionBooking({promotion,live,catalog,lang,t,onBooked}){
 const service=catalog.services.find(s=>s.id===promotion.service_id),business=promotion.business;
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:business.timezone||'America/Mazatlan',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [day,setDay]=useState(today),[slots,setSlots]=useState([]),[chosen,setChosen]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);const lock=useRef(false);
 useEffect(()=>{let active=true;setLoading(true);setChosen('');setError('');supabase.rpc('promotion_slots',{p_promotion:promotion.id,p_day:day}).then(({data,error})=>{if(!active)return;setSlots(error?[]:data||[]);if(error)setError(t.error);setLoading(false);});return()=>{active=false;};},[day,promotion.id,retry]);
 const slot=slots.find(s=>s.collaborator_id+'|'+s.starts_at===chosen);
 async function book(){if(!slot||lock.current)return;lock.current=true;setBusy(true);setError('');try{const click=await live.attribution(promotion);const result=await supabase.rpc('book_promotion',{p_promotion:promotion.id,p_click:click,p_collaborator:slot.collaborator_id,p_start:slot.starts_at});if(result.error)throw result.error;live.clearAttribution(promotion);onBooked(Array.isArray(result.data)?result.data[0]:result.data);}catch{setError(lang==='es'?'No pudimos reservar. Actualiza los horarios e inténtalo de nuevo.':'Could not book. Refresh the available times and try again.');}finally{lock.current=false;setBusy(false);}}
 return <section className="u-promo-booking"><span>{business.name}</span><h2>{service?localized(service,'name',lang):localized(promotion,'title',lang)}</h2><p>{service&&localized(service,'description',lang)}</p><strong className="u-promo-price">{new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(promotion.special_price_mxn)} {service&&' · '+service.duration_minutes+' min'}</strong><p>{localized(promotion,'title',lang)}</p><label>{lang==='es'?'Fecha del servicio':'Service date'}<input type="date" value={day} min={today} max={new Intl.DateTimeFormat('en-CA',{timeZone:business.timezone||'America/Mazatlan',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(promotion.ends_at))} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><small>{lang==='es'?'Hora local del establecimiento':'Establishment local time'} · {business.timezone||'America/Mazatlan'}</small>{loading?<p role="status">{t.contentLoading}</p>:<div className="u-promo-slots">{slots.map(s=><button key={s.collaborator_id+'|'+s.starts_at} className={chosen===s.collaborator_id+'|'+s.starts_at?'selected':''} aria-pressed={chosen===s.collaborator_id+'|'+s.starts_at} onClick={()=>setChosen(s.collaborator_id+'|'+s.starts_at)}>{new Date(s.starts_at).toLocaleTimeString(lang==='es'?'es-MX':'en-US',{timeZone:business.timezone||'America/Mazatlan',hour:'2-digit',minute:'2-digit'})}<small>{s.collaborator_name}</small></button>)}</div>}{!loading&&!slots.length&&!error&&<p>{lang==='es'?'No hay horarios disponibles para esta fecha. Elige otro día; el comercio debe tener reservas y disponibilidad habilitadas.':'No times are available for this date. Choose another day; the business must enable booking and availability.'}</p>}{error&&<p role="alert">{error}</p>}<button className="u-text" disabled={loading||busy} onClick={()=>setRetry(x=>x+1)}>{lang==='es'?'Actualizar horarios':'Refresh times'}</button><button className="u-primary" disabled={!slot||busy||loading} onClick={book}>{busy?t.contentLoading:lang==='es'?'Confirmar reserva':'Confirm booking'}</button><p className="u-promo-terms">{localized(promotion,'terms',lang)}</p></section>;
}

export function LiveCapsule({live,t,lang,catalog,onOpen}){
 const p=live.capsule;if(!p)return null;const category=catalog.categories.find(c=>c.id===p.category_id)||parentCategory(p.business,catalog),parent=catalog.categories.find(c=>c.id===category?.parent_id)||category;
 return <aside className="u-live-capsule" data-promotion={p.id} aria-label={t.availableLive}><button className="u-live-capsule-open" onClick={()=>{live.dismiss();onOpen(p,'capsule');}}><span className="u-live-thumb"><LivePhoto offer={p} catalog={catalog} lang={lang}/></span><span className="u-live-category" title={localized(category,'name',lang)}><Icon name={categoryIcons[parent?.slug]||'leaf'} size={19}/></span><span className="u-live-capsule-text" role="status"><strong>{p.business.name}</strong><span>{localized(p,'title',lang)}{localized(p,'description',lang)?' · '+localized(p,'description',lang):''}</span></span><span className="u-live-badge"><Icon name="live" size={22}/><small>LIVE</small></span></button><button className="u-live-dismiss" onClick={live.dismiss} aria-label={t.close}><Icon name="close" size={12}/></button></aside>;
}
