'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Image from 'next/image';
import Icon from './icons';
import {copy} from './customer-copy';
import {categoryIcons,localized,safeUrl,parentCategory,categoriesFor,distanceKm,rankBusinesses,filterBusinesses} from './discovery-model';
import {supabase,authRedirectUrl} from '../lib/supabase';
import '../customer.css';
const DEFAULT={locale:'es',appearance:'pro',live_enabled:false,display_name:'',interests:[],favorites:[],signals:{}};
function readGuest(){try{const s=JSON.parse(localStorage.getItem('mi-espacio-guest-v1'));return {...DEFAULT,...s,locale:['es','en'].includes(s?.locale)?s.locale:'es',appearance:['pro','modern_teal','warm_neutral'].includes(s?.appearance)?s.appearance:'pro',live_enabled:s?.live_enabled===true,display_name:typeof s?.display_name==='string'?s.display_name:'',interests:Array.isArray(s?.interests)?s.interests:[],favorites:Array.isArray(s?.favorites)?s.favorites:[],signals:s?.signals||{}};}catch{return {...DEFAULT};}}
function PlaceImage({business,images,catalog,lang,priority=false}){const src=safeUrl(business.cover_image_url||images.find(x=>x.is_cover)?.image_url||images[0]?.image_url),[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);const parent=parentCategory(business,catalog);return <div className={'u-place-image tone-'+(parent?.slug||'spa-relajacion')}>{src&&!failed?<Image src={src} alt={localized(images[0],'alt',lang)||business.name} fill sizes="(max-width:600px) 85vw, 380px" unoptimized priority={priority} onError={()=>setFailed(true)}/>:<div className="u-place-art"><div className="u-art-orbit"/><Icon name={categoryIcons[parent?.slug]||'leaf'} size={68}/><span>{parent?localized(parent,'name',lang):'Mi Espacio'}</span></div>}</div>}
function Heading({title,subtitle,action}){return <div className="u-section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Empty({icon='search',title,description,action}){return <section className="u-empty"><span><Icon name={icon} size={33}/></span><h2>{title}</h2><p>{description}</p>{action}</section>}
export default function Customer({initialCatalog}){
 const [catalog,setCatalog]=useState(initialCatalog),[preview,setPreview]=useState(true),[prefs,setPrefs]=useState(DEFAULT),[session,setSession]=useState(null),[profileReady,setProfileReady]=useState(false),[screen,setScreen]=useState(0),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[city,setCity]=useState(''),[photoOnly,setPhotoOnly]=useState(false),[sort,setSort]=useState('recommended'),[geo,setGeo]=useState(null),[selected,setSelected]=useState(null),[detailTab,setDetailTab]=useState(0),[sheet,setSheet]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[visits,setVisits]=useState([]),[rewards,setRewards]=useState([]),[promotions,setPromotions]=useState([]),[calendarTab,setCalendarTab]=useState(0),[visitTab,setVisitTab]=useState(0),[onboarding,setOnboarding]=useState(0),[draftInterests,setDraftInterests]=useState([]),[draftLive,setDraftLive]=useState(false),[catalogError,setCatalogError]=useState(false);
 const lang=prefs.locale,t=copy[lang],dialogRef=useRef(null),toastTimer=useRef(null),userId=session?.user.id;
 const categoryRows=catalog.categories.filter(c=>c.active!==false),parents=categoryRows.filter(c=>!c.parent_id),ranked=useMemo(()=>rankBusinesses(catalog,prefs.interests,prefs.favorites,prefs.signals),[catalog,prefs.interests,prefs.favorites,prefs.signals]);
 const homeCategories=['barberias','faciales','spa-relajacion','unas','fitness','salud','restaurantes','actividades-experiencias'].map(slug=>categoryRows.find(c=>c.slug===slug)).filter(Boolean);
 const homeIcons={barberias:'scissors',faciales:'beauty',unas:'nails',...categoryIcons};
 const filtered=useMemo(()=>filterBusinesses(ranked,catalog,{query,category,city,photoOnly,sort,location:geo}),[ranked,catalog,query,category,city,photoOnly,sort,geo]);
 const featured=(city?ranked.filter(b=>b.city===city):ranked).slice(0,6),related=ranked.filter(b=>b.match.reason==='affinity').slice(0,6),current=selected?catalog.businesses.find(b=>b.id===selected):null;
 const photoRows=current?catalog.gallery.filter(g=>g.business_id===current.id):[],offeringRows=current?catalog.offerings.filter(s=>s.business_id===current.id):[],serviceRows=current?catalog.services.filter(s=>s.business_id===current.id&&s.active):[],reviewRows=current?catalog.reviews.filter(r=>r.business_id===current.id):[];
 function notify(message){setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),5000);}
 async function action(fn){setBusy(true);try{await fn();}catch(e){notify(t.error);console.error('Mi Espacio action failed',e.message);}finally{setBusy(false);}}
 async function loadCatalog(){const {data:businesses,error}=await supabase.from('businesses').select('*').eq('status','published');if(error){setCatalogError(true);return;}setCatalogError(false);if(!businesses.length){setCatalog(initialCatalog);setPreview(true);return;}const ids=businesses.map(b=>b.id);const tables={gallery:'business_gallery',offerings:'business_service_offerings',reviews:'business_reviews',services:'services',business_categories:'business_categories'};const results=await Promise.all(Object.entries(tables).map(async([key,table])=>{let req=supabase.from(table).select('*').in('business_id',ids);if(['gallery','reviews'].includes(key))req=req.eq('status','published');const result=await req;if(result.error)throw result.error;return [key,result.data];}));setCatalog({...initialCatalog,businesses,...Object.fromEntries(results)});setPreview(false);}
 useEffect(()=>{setPrefs(readGuest());loadCatalog().catch(()=>setCatalogError(true));const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setSheet('new-password');});return()=>{subscription.unsubscribe();clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 useEffect(()=>{if(!userId){setPrefs(readGuest());setProfileReady(true);setVisits([]);setRewards([]);return;}setProfileReady(false);let disposed=false;async function load(){const results=await Promise.all([supabase.from('profiles').select('*').eq('user_id',userId).maybeSingle(),supabase.from('user_interests').select('*').eq('user_id',userId).order('slot'),supabase.from('favorites').select('*').eq('customer_id',userId),supabase.from('user_category_signals').select('*').eq('user_id',userId),supabase.from('visits').select('*').eq('customer_id',userId).order('starts_at',{ascending:false}),supabase.from('reward_ledger').select('*').eq('customer_id',userId)]);const error=results.find(r=>r.error)?.error;if(error)throw error;if(disposed)return;const [profile,interests,favs,signals,citas,ledger]=results.map(r=>r.data);setPrefs({...DEFAULT,...profile,display_name:profile?.display_name||session.user.user_metadata?.display_name||session.user.email?.split('@')[0]||'',interests:interests.map(i=>i.category_id),favorites:favs.map(f=>f.business_id),signals:Object.fromEntries(signals.filter(s=>s.signal==='view'||s.signal==='save').map(s=>[s.category_id,1]))});setVisits(citas);setRewards(ledger);setProfileReady(true);}load().catch(e=>{if(!disposed)notify(t.error);});return()=>{disposed=true;};},[userId]);
 useEffect(()=>{if(!prefs.live_enabled||!userId){setPromotions([]);return;}let active=true;supabase.from('promotions').select('*').eq('placement','live').eq('status','published').then(({data,error})=>{if(active&&!error)setPromotions(data.filter(p=>new Date(p.starts_at)<=new Date()&&new Date(p.ends_at)>new Date()));});return()=>{active=false;};},[userId,prefs.live_enabled]);
 useEffect(()=>{const slug=new URLSearchParams(window.location.search).get('negocio');if(slug){const b=catalog.businesses.find(b=>b.slug===slug);if(b)setSelected(b.id);}const pop=()=>{const slug=new URLSearchParams(window.location.search).get('negocio');setSelected(catalog.businesses.find(b=>b.slug===slug)?.id||null);};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[catalog]);
 useEffect(()=>{if(selected&&!sheet)document.querySelector('.u-detail-toolbar button')?.focus();},[selected,sheet]);
 useEffect(()=>{if(!sheet)return;const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=dialogRef.current;const first=dialog?.querySelector('button,input,select');first?.focus();const keyboard=e=>{if(e.key==='Escape')setSheet(null);if(e.key==='Tab'){const elements=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select,a[href]')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keyboard);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',keyboard);previous?.focus();};},[sheet]);
 function persistGuest(next){localStorage.setItem('mi-espacio-guest-v1',JSON.stringify(next));}
 async function changePrefs(patch){const next={...prefs,...patch};if(userId){if(!profileReady)throw Error('Profile unavailable');const {error}=await supabase.from('profiles').upsert({user_id:userId,display_name:next.display_name||t.guest,locale:next.locale,appearance:next.appearance,live_enabled:next.live_enabled});if(error)throw error;}else persistGuest(next);setPrefs(next);}
 async function saveInterests(){await action(async()=>{if(userId){if(!profileReady)throw Error('Profile unavailable');const {error}=await supabase.rpc('set_interests',{p_categories:draftInterests});if(error)throw error;}await changePrefs({interests:draftInterests,live_enabled:draftLive});setSheet(null);notify(t.prefsSaved);});}
 function startPreferences(){setDraftInterests(prefs.interests);setDraftLive(prefs.live_enabled);setOnboarding(0);setSheet('preferences');}
 async function favorite(b){await action(async()=>{const exists=prefs.favorites.includes(b.id);const next={...prefs,favorites:exists?prefs.favorites.filter(id=>id!==b.id):[...prefs.favorites,b.id]};if(userId){if(preview){notify(t.previewDetails);return;}const req=exists?supabase.from('favorites').delete().eq('customer_id',userId).eq('business_id',b.id):supabase.from('favorites').insert({customer_id:userId,business_id:b.id});const {error}=await req;if(error)throw error;}else persistGuest(next);setPrefs(next);notify(exists?t.removeSaved:t.saved);});}
 function recordView(b){const next={...prefs,signals:{...prefs.signals,[b.category_id]:Math.min(10,(prefs.signals[b.category_id]||0)+1)}};setPrefs(next);if(!userId)persistGuest(next);else if(profileReady)supabase.from('user_category_signals').upsert({user_id:userId,category_id:b.category_id,signal:'view',last_seen_at:new Date().toISOString()}).then(({error})=>{if(error)console.error('Signal not saved');});}
 function openPlace(b){recordView(b);setSelected(b.id);setDetailTab(0);const url=new URL(window.location.href);url.searchParams.set('negocio',b.slug);window.history.pushState({place:b.id},'',url);window.scrollTo(0,0);}
 function closePlace(){setSelected(null);const url=new URL(window.location.href);url.searchParams.delete('negocio');window.history.replaceState({},'',url);window.scrollTo(0,0);}
 function navigate(n){closePlace();setScreen(n);setSheet(null);window.scrollTo({top:0,behavior:'instant'});}
 function explore(cat=''){setCategory(cat);setQuery('');navigate(1);}
 function locate(){if(!navigator.geolocation){notify(t.geoDenied);return;}navigator.geolocation.getCurrentPosition(({coords})=>{setGeo({latitude:coords.latitude,longitude:coords.longitude});setSort('near');},()=>notify(t.geoDenied),{timeout:10000,maximumAge:300000});}
 async function auth(e,mode){e.preventDefault();const form=Object.fromEntries(new FormData(e.target));await action(async()=>{if(mode==='recover'){const {error}=await supabase.auth.resetPasswordForEmail(form.email,{redirectTo:authRedirectUrl});if(error)throw error;notify(t.recoverySent);return;}if(mode==='new-password'){const {error}=await supabase.auth.updateUser({password:form.password});if(error)throw error;setSheet(null);notify(t.passwordUpdated);return;}const response=mode==='signup'?await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:authRedirectUrl,data:{display_name:form.name}}}):await supabase.auth.signInWithPassword({email:form.email,password:form.password});if(response.error)throw response.error;if(mode==='signup'&&!response.data.session)notify(t.sent);else setSheet(null);});}
 async function share(b){const url=new URL('/',window.location.origin);url.searchParams.set('negocio',b.slug);try{if(navigator.share)await navigator.share({title:b.name,text:localized(b,'short_description',lang),url:url.href});else{await navigator.clipboard.writeText(url.href);notify(t.copied);}}catch(e){if(e.name!=='AbortError')notify(t.error);}}
 function card(b,compact=false){const images=catalog.gallery.filter(g=>g.business_id===b.id),parent=parentCategory(b,catalog),distance=distanceKm(b,geo);return <article key={b.id} className={'u-place-card'+(compact?' compact':'')}><div className="u-card-visual"><button className="u-image-button" aria-label={t.viewPlace+' · '+b.name} onClick={()=>openPlace(b)}><PlaceImage business={b} images={images} catalog={catalog} lang={lang}/></button><span className="u-photo-tag">{t.categoryNames[parent?.slug]||localized(parent,'name',lang)}</span><button className={'u-heart'+(prefs.favorites.includes(b.id)?' is-saved':'')} aria-label={(prefs.favorites.includes(b.id)?t.removeSaved:t.save)+' · '+b.name} disabled={busy} onClick={()=>favorite(b)}><Icon name="heart" size={19} filled={prefs.favorites.includes(b.id)}/></button></div><div className="u-card-content"><div className="u-card-category">{b.match?.reason&&<span><Icon name="spark" size={12}/>{t[{interest:'basedInterest',activity:'basedActivity',affinity:'basedAffinity'}[b.match.reason]]}</span>}<span>{b.listing_review_status==='approved'?t.verified:t.pending}</span></div><button className="u-title-button" onClick={()=>openPlace(b)}><h3>{b.name}</h3></button><p className="u-card-location"><Icon name="pin" size={13}/>{b.area||b.city}{distance!=null&&<span> · {distance.toFixed(1)} km</span>}</p>{!compact&&<p className="u-card-description">{localized(b,'short_description',lang)}</p>}<div className="u-card-footer"><button onClick={()=>openPlace(b)}>{t.viewPlace}<Icon name="arrow" size={16}/></button>{safeUrl(b.maps_url)&&<a href={safeUrl(b.maps_url)} target="_blank" rel="noreferrer" aria-label={t.directions+' · '+b.name}><Icon name="pin" size={15}/>{t.directions}</a>}</div></div></article>}
 const resultsGrid=rows=>rows.length?<div className="u-results-grid">{rows.map(b=>card(b))}</div>:<Empty title={t.empty} description={t.emptySearch} action={<button className="u-primary" onClick={()=>{setCategory('');setQuery('');setCity('');setPhotoOnly(false);}}>{t.clear}</button>}/>;
 const sheetTitle={'filters':t.filters,'location':t.location,'preferences':onboarding===0?t.prefsTitle:t.liveStep,'auth':t.signIn,'signup':t.signUp,'recover':t.forgot,'new-password':t.newPassword,'live':t.availableLive,'booking':t.bookingSoon}[sheet];
 return <div className={'consumer theme-'+prefs.appearance+(screen===0?' u-home-screen':'')}>
 <header className="u-header" inert={!!(current||sheet)} aria-hidden={!!(current||sheet)}><a className="u-wordmark" href="/" aria-label="Mi Espacio"><span>me.</span><strong>Mi Espacio<small>{t.tagline}</small></strong></a><div className="u-header-actions"><button className="u-locale" aria-label={t.language} onClick={()=>action(()=>changePrefs({locale:lang==='es'?'en':'es'}))}>{lang.toUpperCase()}<Icon name="globe" size={14}/></button><button className="u-profile-icon" aria-label={t.nav[4]} onClick={()=>navigate(4)}><Icon name="user" size={20}/></button></div></header>
 {preview&&<button className="u-preview-strip" onClick={()=>notify(t.previewDetails)}><Icon name="shield" size={12}/>{t.preview}<Icon name="chevron" size={12}/></button>}
 <main className="u-main" inert={!!(current||sheet)} aria-hidden={!!(current||sheet)}>
 {screen===0&&<><div className="u-home-context"><button onClick={()=>setSheet('location')}><Icon name="pin" size={15}/>{city||t.allCabo}<Icon name="chevron" size={13}/></button><button className={'u-live-status'+(prefs.live_enabled?' enabled':'')} role="switch" aria-checked={prefs.live_enabled} aria-label={prefs.live_enabled?t.liveOn:t.liveOff} onClick={()=>action(()=>changePrefs({live_enabled:!prefs.live_enabled}))}><i/>{prefs.live_enabled?t.liveOn:t.liveOff}</button></div><div className="u-greeting"><span>{session&&prefs.display_name?(lang==='es'?'HOLA, ':'HELLO, ')+prefs.display_name.toUpperCase():(lang==='es'?'MI ESPACIO, TU MOMENTO':'MI ESPACIO, YOUR MOMENT')}</span><h1>{t.welcome}</h1><p>{t.welcomeSub}</p></div><form className="u-search" onSubmit={e=>{e.preventDefault();navigate(1);}}><Icon name="search" size={21}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label={t.nav[1]}><Icon name="arrow" size={19}/></button></form><section className="u-category-section"><Heading title={t.categories}/><div className="u-category-scroll">{homeCategories.map(c=><button key={c.id} onClick={()=>explore(c.id)}><span className={'u-category-icon tone-'+c.slug}><Icon name={homeIcons[c.slug]} size={24}/></span><strong>{t.homeCategoryNames[c.slug]||t.categoryNames[c.slug]||localized(c,'name',lang)}</strong></button>)}</div></section>
 <section className="u-moment-banner"><div><span>BIENESTAR · WELLNESS</span><h2>{lang==='es'?<>Menos prisa.<br/>Más <em>tú.</em></>:<>Less rush.<br/>More <em>you.</em></>}</h2><p>{lang==='es'?'Encuentra tu próxima pausa en Los Cabos.':'Find your next pause in Los Cabos.'}</p><button onClick={()=>explore(parents.find(p=>p.slug==='spa-relajacion')?.id)}>{t.discover}<Icon name="arrow" size={17}/></button></div><div className="u-banner-art" aria-hidden="true"><div className="u-arch arch-one"/><div className="u-arch arch-two"/><div className="u-sun-disc"/><div className="u-leaf-shape"/><span>me.</span><svg viewBox="0 0 230 170"><path d="M0 145C60 150 30 55 100 80s70 55 130 5M0 166c70-7 44-100 105-56s82 10 125-53" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></div></section>
 <section className="u-home-places"><Heading title={t.forYou} subtitle={t.forYouSub} action={<button className="u-text" onClick={()=>explore()}>{t.seeAll}<Icon name="arrow" size={15}/></button>}/><div className="u-horizontal-cards">{featured.map(b=>card(b,true))}</div></section>
 {!prefs.interests.length&&<section className="u-personalize"><span className="u-personalize-icon"><Icon name="spark" size={24}/></span><div><h3>{t.personalize}</h3><p>{t.personalizeSub}</p><button onClick={startPreferences}>{t.choose}<Icon name="arrow" size={15}/></button></div></section>}
 {related.length>0&&<section className="u-home-places"><Heading title={t.related} subtitle={t.relatedSub}/><div className="u-horizontal-cards">{related.map(b=>card(b,true))}</div></section>}
 <section className={'u-live-banner'+(prefs.live_enabled?' enabled':'')}><Icon name="live" size={30}/><div><span>MI ESPACIO LIVE</span><h3>{t.liveTitle}</h3><p>{t.liveDescription}</p><button onClick={()=>prefs.live_enabled?setSheet('live'):action(()=>changePrefs({live_enabled:true}))}>{prefs.live_enabled?t.availableLive:t.activate}<Icon name="arrow" size={16}/></button></div></section>
 </>}
 {screen===1&&<><div className="u-page-heading"><span>LOS CABOS</span><h1>{t.nav[1]}</h1><p>{t.forYouSub}</p></div><div className="u-explore-controls"><form className="u-search" onSubmit={e=>e.preventDefault()}><Icon name="search"/><input aria-label={t.searchExplore} placeholder={t.searchExplore} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label={t.clear} onClick={()=>setQuery('')}><Icon name="close" size={18}/></button>}<button type="button" className="u-filter-button" aria-label={t.filters} onClick={()=>setSheet('filters')}><Icon name="filter" size={20}/></button></form><div className="u-filter-chips"><button className={!category?'selected':''} onClick={()=>setCategory('')}>{t.all}</button>{parents.map(c=><button key={c.id} className={category===c.id?'selected':''} onClick={()=>setCategory(c.id)}>{t.categoryNames[c.slug]||localized(c,'name',lang)}</button>)}</div></div><div className="u-results-meta"><span>{filtered.length} {t.results}</span><button onClick={()=>setSheet('filters')}><Icon name="filter" size={14}/>{city||t[{recommended:'sortRecommended',name:'sortName',near:'sortNear'}[sort]]}</button></div>{resultsGrid(filtered)}</>}
 {screen===3&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.nav[3]}</h1><p>{t.favoritesSub}</p></div>{prefs.favorites.length?resultsGrid(ranked.filter(b=>prefs.favorites.includes(b.id))):<Empty icon="heart" title={t.emptyFavorites} description={t.emptyFavoritesSub} action={<button className="u-primary" onClick={()=>explore()}>{t.explore}<Icon name="arrow" size={17}/></button>}/>}</>}
 {screen===2&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.appointmentsTitle}</h1><p>{t.appointmentsSub}</p></div><div className="u-segments">{[t.appointments,t.rewards].map((label,n)=><button key={n} onClick={()=>setCalendarTab(n)} className={calendarTab===n?'selected':''}>{label}</button>)}</div>{calendarTab===0?<><div className="u-mini-tabs">{[t.upcoming,t.history].map((label,n)=><button className={visitTab===n?'selected':''} onClick={()=>setVisitTab(n)} key={n}>{label}</button>)}</div>{visits.filter(v=>visitTab===0?['scheduled','checked_in'].includes(v.status):!['scheduled','checked_in'].includes(v.status)).length?visits.filter(v=>visitTab===0?['scheduled','checked_in'].includes(v.status):!['scheduled','checked_in'].includes(v.status)).map(v=><article className="u-visit" key={v.id}><Icon name="calendar"/><div><strong>{catalog.businesses.find(b=>b.id===v.business_id)?.name||'Mi Espacio'}</strong><p>{v.starts_at&&new Date(v.starts_at).toLocaleString(lang==='es'?'es-MX':'en-US',{timeZone:'America/Mazatlan',dateStyle:'medium',timeStyle:'short'})}</p><span>{t.status[v.status]}</span></div></article>):<Empty icon="calendar" title={t.noAppointments} description={t.noAppointmentsSub} action={<button className="u-primary" onClick={()=>explore()}>{t.explore}</button>}/>}</>:<><section className="u-reward-card"><Icon name="wallet" size={30}/><p>{t.collected}</p><strong>{new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(rewards.reduce((sum,r)=>sum+Number(r.credit_mxn),0))}</strong><span>MXN</span><small>{t.rewardsInfo}</small></section>{rewards.length?rewards.map(r=><article className="u-visit" key={r.id}><Icon name="wallet"/><div><strong>{catalog.businesses.find(b=>b.id===r.business_id)?.name||'Mi Espacio'}</strong><p>+{r.credit_mxn} MXN</p></div></article>):<Empty icon="spark" title={t.noRewards} description={t.noRewardsSub}/>}</>}</>}
 {screen===4&&<><div className="u-page-heading"><span>MI ESPACIO</span><h1>{t.profileTitle}</h1></div><section className="u-profile-card"><span className="u-large-avatar">{prefs.display_name?.charAt(0)?.toUpperCase()||<Icon name="user" size={32}/>}</span><h2>{prefs.display_name||t.guest}</h2><p>{session?session.user.email:t.guestDescription}</p>{!session&&<button className="u-primary" onClick={()=>setSheet('auth')}>{t.signIn}<Icon name="arrow" size={16}/></button>}</section><section className="u-account-note"><strong>{session?t.accountMode:t.guestMode}</strong><p>{session?t.accountScope:t.guestScope}</p></section><section className="u-settings-group"><div className="u-setting-title"><h2>{t.interests}</h2><button className="u-text" onClick={startPreferences}>{t.edit}<Icon name="chevron" size={15}/></button></div><div className="u-interest-labels">{prefs.interests.length?prefs.interests.map(id=><span key={id}>{localized(categoryRows.find(c=>c.id===id),'name',lang)}</span>):<button className="u-text" onClick={startPreferences}>{t.choose}<Icon name="arrow" size={15}/></button>}</div><div className="u-setting-row"><span className="u-setting-icon"><Icon name="live"/></span><div><strong>Mi Espacio Live</strong><p>{t.liveHelp}</p></div><button className={'u-switch'+(prefs.live_enabled?' on':'')} role="switch" aria-checked={prefs.live_enabled} aria-label="Mi Espacio Live" disabled={busy} onClick={()=>action(()=>changePrefs({live_enabled:!prefs.live_enabled}))}><i/></button></div><div className="u-setting-row"><span className="u-setting-icon"><Icon name="globe"/></span><div><strong>{t.language}</strong></div><div className="u-language-options"><button disabled={busy} className={lang==='es'?'selected':''} onClick={()=>action(()=>changePrefs({locale:'es'}))}>ES</button><button disabled={busy} className={lang==='en'?'selected':''} onClick={()=>action(()=>changePrefs({locale:'en'}))}>EN</button></div></div></section><section className="u-settings-group"><h2>{t.appearance}</h2><div className="u-palette-options">{[['pro','Pro'],['modern_teal','Modern Teal'],['warm_neutral','Warm Neutral']].map(([p,label])=><button key={p} disabled={busy} aria-pressed={prefs.appearance===p} className={prefs.appearance===p?'selected':''} onClick={()=>action(()=>changePrefs({appearance:p}))}><span className={'u-palette-swatch '+p}/><strong>{label}</strong>{prefs.appearance===p&&<Icon name="check" size={16}/>}</button>)}</div></section><a className="u-commerce-link" href="/comercio"><div><strong>{t.commerce}</strong><span>{t.commerceLink}</span></div><Icon name="arrow"/></a>{session?<button className="u-sign-out" onClick={()=>action(async()=>{const {error}=await supabase.auth.signOut();if(error)throw error;})}><Icon name="logout" size={18}/>{t.signOut}</button>:<button className="u-reset" onClick={()=>{localStorage.removeItem('mi-espacio-guest-v1');setPrefs({...DEFAULT});notify(t.prefsSaved);}}>{t.resetPreview}</button>}</>}
 {catalogError&&<button className="u-retry" onClick={()=>loadCatalog().catch(()=>notify(t.error))}>{t.retry}<Icon name="arrow" size={13}/></button>}
 <div className="u-bottom-signature"><span>me.</span><p>{t.tagline}</p></div>
 </main>
 <nav className="u-bottom-nav" inert={!!(current||sheet)} aria-hidden={!!(current||sheet)} aria-label={lang==='es'?'Navegación principal':'Main navigation'}>{t.nav.map((label,n)=><button key={n} className={screen===n?'selected':''} aria-current={screen===n?'page':undefined} onClick={()=>navigate(n)}><span><Icon name={['home','search','calendar','heart','user'][n]} size={22}/>{n===3&&prefs.favorites.length>0&&<i>{prefs.favorites.length}</i>}</span><strong>{label}</strong></button>)}</nav>
 {current&&<div className="u-detail-view" role="dialog" aria-modal="true" aria-label={current.name} inert={!!sheet} aria-hidden={!!sheet}><div className="u-detail-content"><header className="u-detail-toolbar"><button className="u-round-button" aria-label={t.back} onClick={closePlace}><Icon name="back"/></button><strong>{current.name}</strong><button className="u-round-button" aria-label={t.share} onClick={()=>share(current)}><Icon name="share" size={19}/></button><button className={'u-round-button'+(prefs.favorites.includes(current.id)?' is-saved':'')} aria-label={(prefs.favorites.includes(current.id)?t.removeSaved:t.save)+' · '+current.name} disabled={busy} onClick={()=>favorite(current)}><Icon name="heart" size={19} filled={prefs.favorites.includes(current.id)}/></button></header><div className="u-detail-hero"><PlaceImage business={current} images={photoRows} catalog={catalog} lang={lang} priority/><span>{photoRows.length?photoRows.length+' '+t.photos:t.photoPending}</span></div><div className="u-detail-intro"><span className="u-detail-category">{t.categoryNames[parentCategory(current,catalog)?.slug]} · {current.city}</span><h1>{current.name}</h1><p>{localized(current,'short_description',lang)}</p><div className="u-detail-status"><Icon name="shield" size={15}/>{current.listing_review_status==='approved'?t.verified:t.pending}</div></div><div className="u-detail-tabs">{[t.about,t.services,t.photos,t.reviews].map((label,n)=><button key={n} className={detailTab===n?'selected':''} onClick={()=>setDetailTab(n)}>{label}</button>)}</div><div className="u-detail-body">
 {detailTab===0&&<><section><h2>{t.about}</h2><p>{localized(current,'description',lang)}</p></section><section><h2>{t.address}</h2><div className="u-address-card"><Icon name="pin" size={23}/><div><strong>{current.address||current.city}</strong><p>{localized(current,'directions',lang)}</p>{safeUrl(current.maps_url)&&<a className="u-text" href={safeUrl(current.maps_url)} target="_blank" rel="noreferrer">{t.directions}<Icon name="arrow" size={15}/></a>}</div></div></section>{localized(current,'opening_hours',lang)&&<section><h2>{t.hours}</h2><div className="u-hours"><Icon name="clock"/><p>{localized(current,'opening_hours',lang)}</p></div></section>}<section><h2>{t.contact}</h2><div className="u-contact-links">{current.phone&&<a href={'tel:'+current.phone.split('ext.')[0].replace(/[^+\d]/g,'')}><Icon name="phone"/>{current.phone}<Icon name="arrow" size={16}/></a>}{safeUrl(current.website_url)&&<a href={safeUrl(current.website_url)} target="_blank" rel="noreferrer"><Icon name="globe"/>{t.website}<Icon name="arrow" size={16}/></a>}</div></section>{current.enrollment_status==='active'&&<div className="u-benefit"><Icon name="spark"/><div><strong>{Math.round(current.reward_rate*100)}% · {t.rewardRate}</strong><p>{t.rewardsInfo}</p></div></div>}</>}
 {detailTab===1&&<><h2>{t.services}</h2>{serviceRows.length?serviceRows.map(s=><article className="u-service-row" key={s.id}><div><h3>{localized(s,'name',lang)}</h3><p>{localized(s,'description',lang)}</p><span><Icon name="clock" size={13}/>{s.duration_minutes} min · {new Intl.NumberFormat(lang==='es'?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(s.price_mxn)}</span></div><button aria-label={t.ask+' · '+localized(s,'name',lang)} onClick={()=>setSheet('booking')}><Icon name="chevron" size={19}/></button></article>):offeringRows.map(s=><article className="u-service-row" key={s.id}><div><h3>{localized(s,'title',lang)}</h3><p>{localized(s,'description',lang)}</p><span>{t.price} / {t.duration}: {t.confirming}</span></div><span className="u-service-pending"><Icon name="clock" size={17}/></span></article>)}{!serviceRows.length&&!offeringRows.length&&<Empty icon="leaf" title={t.confirming} description={t.bookingInfo}/>}<p className="u-detail-note">{t.bookingInfo}</p></>}
 {detailTab===2&&<><h2>{t.photos}</h2>{photoRows.length?<div className="u-gallery-grid">{photoRows.map(p=><figure key={p.id}><PlaceImage business={{...current,cover_image_url:p.image_url}} images={[p]} catalog={catalog} lang={lang}/><figcaption>{localized(p,'caption',lang)}{p.source_url&&<a href={safeUrl(p.source_url)||'#'} target="_blank" rel="noreferrer">{t.source}<Icon name="arrow" size={12}/></a>}</figcaption></figure>)}</div>:<Empty icon="image" title={t.photoPending} description={t.researchNotice}/>}</>}
 {detailTab===3&&<><h2>{t.reviews}</h2><p className="u-review-notice"><Icon name="shield" size={15}/>{t.noRatings}</p>{reviewRows.map(r=><article className="u-review" key={r.id}><span>{r.kind==='editorial'?t.editorial:t.researchNote}</span><p>{localized(r,'body',lang)}</p>{safeUrl(r.source_url)&&<a className="u-text" href={safeUrl(r.source_url)} target="_blank" rel="noreferrer">{r.source_label||t.source}<Icon name="arrow" size={14}/></a>}</article>)}</>}
 {preview&&<p className="u-research-notice"><Icon name="shield" size={16}/>{t.researchNotice}</p>}
 </div></div><div className="u-detail-actions"><a className="u-primary" href={safeUrl(current.maps_url)||safeUrl(current.website_url)||'#'} target="_blank" rel="noreferrer"><Icon name="pin" size={18}/>{t.directions}</a><button className="u-secondary" onClick={()=>setSheet('booking')}><Icon name="calendar" size={18}/>{t.bookingSoon}</button></div></div>}
 {sheet&&<div className="u-sheet-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSheet(null);}}><section ref={dialogRef} className={'u-sheet '+(sheet==='preferences'?'u-onboarding':'')} role="dialog" aria-modal="true" aria-labelledby="sheet-title"><header className="u-sheet-header"><div className="u-sheet-handle"/><div><h2 id="sheet-title">{sheetTitle}</h2><button aria-label={t.close} className="u-round-button" onClick={()=>setSheet(null)}><Icon name="close" size={21}/></button></div></header><div className="u-sheet-body">
 {['filters','location'].includes(sheet)&&<><label className="u-field"><span>{t.city}</span><select aria-label={t.city} value={city} onChange={e=>setCity(e.target.value)}><option value="">{t.allCities}</option>{[...new Set(catalog.businesses.map(b=>b.city))].filter(Boolean).map(c=><option key={c}>{c}</option>)}</select></label>{sheet==='filters'&&<><label className="u-field"><span>{t.category}</span><select aria-label={t.category} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{categoryRows.map(c=><option key={c.id} value={c.id}>{localized(c,'name',lang)}</option>)}</select></label><label className="u-field"><span>{t.sort}</span><select aria-label={t.sort} value={sort} onChange={e=>{setSort(e.target.value);if(e.target.value==='near'&&!geo)locate();}}><option value="recommended">{t.sortRecommended}</option><option value="name">{t.sortName}</option><option value="near">{t.sortNear}</option></select></label><label className="u-checkbox"><input type="checkbox" checked={photoOnly} onChange={e=>setPhotoOnly(e.target.checked)}/>{t.photoOnly}</label></>}<button className="u-location-button" onClick={locate}><Icon name="pin" size={18}/>{t.nearMe}</button><button className="u-primary u-full" onClick={()=>{setSheet(null);if(sheet==='filters')setScreen(1);}}>{t.apply}<Icon name="arrow" size={17}/></button></>}
 {sheet==='preferences'&&(onboarding===0?<><p className="u-overline">{t.stepOne}</p><p>{t.prefsSub}</p><div className="u-interest-counter">{draftInterests.length} / 3 {t.selected}</div><div className="u-interest-grid">{categoryRows.filter(c=>c.parent_id).map(c=>{const checked=draftInterests.includes(c.id),parent=categoryRows.find(p=>p.id===c.parent_id);return <button key={c.id} className={checked?'selected':''} aria-pressed={checked} disabled={!checked&&draftInterests.length===3} onClick={()=>setDraftInterests(checked?draftInterests.filter(id=>id!==c.id):[...draftInterests,c.id])}><Icon name={categoryIcons[parent?.slug]} size={20}/><span>{localized(c,'name',lang)}</span>{checked&&<Icon name="check" size={16}/>}</button>})}</div><button disabled={draftInterests.length!==3} className="u-primary u-full" onClick={()=>setOnboarding(1)}>{t.next}<Icon name="arrow" size={18}/></button><button className="u-skip" onClick={()=>setSheet(null)}>{t.skip}</button></>:<><p className="u-overline">{t.stepTwo}</p><div className="u-live-onboard-art"><Icon name="live" size={55}/></div><p>{t.liveStepSub}</p><button className={'u-choice'+(draftLive?'selected':'')} aria-pressed={draftLive} onClick={()=>setDraftLive(true)}><Icon name="live"/><strong>{t.liveYes}</strong>{draftLive&&<Icon name="check" size={17}/>}</button><button className={'u-choice'+(!draftLive?'selected':'')} aria-pressed={!draftLive} onClick={()=>setDraftLive(false)}><Icon name="leaf"/><strong>{t.liveNo}</strong>{!draftLive&&<Icon name="check" size={17}/>}</button><button className="u-primary u-full" disabled={busy} onClick={saveInterests}>{t.finish}<Icon name="arrow" size={17}/></button><button className="u-skip" onClick={()=>setOnboarding(0)}>{t.back}</button></>)}
 {['auth','signup','recover','new-password'].includes(sheet)&&<form onSubmit={e=>auth(e,sheet)}>{sheet==='signup'&&<label className="u-field"><span>{t.name}</span><input name="name" autoComplete="name" required/></label>}{sheet!=='new-password'&&<label className="u-field"><span>{t.email}</span><input name="email" type="email" autoComplete="email" required/></label>}{sheet!=='recover'&&<label className="u-field"><span>{sheet==='new-password'?t.newPassword:t.password}</span><input name="password" type="password" autoComplete={sheet==='auth'?'current-password':'new-password'} minLength={6} required/></label>}<button disabled={busy} className="u-primary u-full">{sheet==='recover'?t.forgot:sheet==='signup'?t.signUp:sheet==='new-password'?t.updatePassword:t.enter}<Icon name="arrow" size={17}/></button>{sheet==='auth'&&<><button type="button" className="u-skip" onClick={()=>setSheet('recover')}>{t.forgot}</button><button type="button" className="u-secondary u-full" onClick={()=>setSheet('signup')}>{t.signUp}</button></>}{sheet==='signup'&&<button type="button" className="u-skip" onClick={()=>setSheet('auth')}>{t.signIn}</button>}</form>}
 {sheet==='live'&&(promotions.length?promotions.map(p=><article className="u-live-offer" key={p.id}><span>LIVE</span><h3>{localized(p,'title',lang)}</h3><p>{localized(p,'description',lang)}</p><small>{new Date(p.ends_at).toLocaleString(lang==='es'?'es-MX':'en-US',{timeZone:'America/Mazatlan'})}</small></article>):<Empty icon="live" title={t.noLive} description={userId?t.noLiveSub:t.liveLogin} action={!userId&&<button className="u-primary" onClick={()=>setSheet('auth')}>{t.signIn}</button>}/>)}
 {sheet==='booking'&&<Empty icon="calendar" title={t.bookingSoon} description={t.bookingInfo} action={current?.phone&&<a className="u-primary" href={'tel:'+current.phone.split('ext.')[0].replace(/[^+\d]/g,'')}><Icon name="phone" size={17}/>{t.ask}</a>}/>}
 </div></section></div>}
 {toast&&<div className="u-toast" role="status"><Icon name="check" size={17}/><span>{toast}</span><button aria-label={t.close} onClick={()=>setToast('')}><Icon name="close" size={15}/></button></div>}
 </div>;
}
