'use client';
import {useEffect,useRef,useState} from 'react';
import Icon from './icons';
import {localized,safeUrl} from './discovery-model';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
export default function GalleryViewer({photos,initialIndex=0,businessName,lang,onClose}){
 const [index,setIndex]=useState(initialIndex),[view,setView]=useState({scale:1,x:0,y:0}),[failed,setFailed]=useState(false);
 const dialog=useRef(null),stage=useRef(null),photo=useRef(null),model=useRef(view),points=useRef(new Map()),gesture=useRef(null),lastTap=useRef(null),close=useRef(onClose);
 close.current=onClose;const row=photos[index],src=safeUrl(row?.image_url),es=lang==='es';
 function apply(next,bounded=false){if(bounded){const image=photo.current,area=stage.current;if(image&&area){const x=Math.max(0,(image.clientWidth*next.scale-area.clientWidth)/2),y=Math.max(0,(image.clientHeight*next.scale-area.clientHeight)/2);next={...next,x:clamp(next.x,-x,x),y:clamp(next.y,-y,y)};}}model.current=next;setView(next);}
 function reset(){points.current.clear();gesture.current=null;lastTap.current=null;apply({scale:1,x:0,y:0});}
 function move(delta){setIndex(i=>(i+delta+photos.length)%photos.length);}
 useEffect(()=>{reset();setFailed(false);},[index]);
 useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector('button')?.focus();const keyboard=e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close.current();}if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}};const resize=()=>reset();document.addEventListener('keydown',keyboard,true);window.addEventListener('resize',resize);const wheel=e=>{if(e.ctrlKey){e.preventDefault();zoom(model.current.scale+(e.deltaY<0?.25:-.25));}};const area=stage.current;area?.addEventListener('wheel',wheel,{passive:false});return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keyboard,true);window.removeEventListener('resize',resize);area?.removeEventListener('wheel',wheel);previous?.focus();};},[]);
 function seed(suppressTap=false){const p=[...points.current.values()];if(p.length>=2){const a=p[0],b=p[1];gesture.current={kind:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),mid:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},base:{...model.current}};}else if(p.length===1)gesture.current={kind:'single',start:p[0],base:{...model.current},suppressTap};else gesture.current=null;}
 function down(e){if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});seed();}
 function drag(e){if(!points.current.has(e.pointerId))return;e.preventDefault();points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture.current,p=[...points.current.values()];if(!g)return;if(g.kind==='pinch'&&p.length>=2){const distance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);const mid={x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2},rect=stage.current.getBoundingClientRect(),anchor={x:g.mid.x-(rect.left+rect.width/2),y:g.mid.y-(rect.top+rect.height/2)};const scale=clamp(g.base.scale*distance/Math.max(1,g.distance),1,4),ratio=scale/g.base.scale;apply({scale,x:(g.base.x-anchor.x)*ratio+anchor.x+mid.x-g.mid.x,y:(g.base.y-anchor.y)*ratio+anchor.y+mid.y-g.mid.y},true);}else if(g.kind==='single'&&p.length===1){const dx=p[0].x-g.start.x,dy=p[0].y-g.start.y;apply({scale:g.base.scale,x:g.base.x+dx,y:g.base.y+dy},g.base.scale>1);}}
 function up(e,cancelled=false){if(!points.current.has(e.pointerId))return;const g=gesture.current,end=points.current.get(e.pointerId),hadPinch=g?.kind==='pinch';points.current.delete(e.pointerId);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(hadPinch){lastTap.current=null;seed(true);return;}if(points.current.size){seed();return;}gesture.current=null;if(cancelled){apply({...model.current,x:0,y:0},true);return;}if(!g)return;const dx=end.x-g.start.x,dy=end.y-g.start.y;if(g.base.scale===1&&!g.suppressTap){if(dy>85&&dy>Math.abs(dx)*1.2){close.current();return;}if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.2&&photos.length>1){move(dx<0?1:-1);return;}}if(!g.suppressTap&&Math.hypot(dx,dy)<12){const now=performance.now(),previous=lastTap.current;if(previous&&now-previous.time<320&&Math.hypot(end.x-previous.x,end.y-previous.y)<30){zoom(model.current.scale>1?1:2);lastTap.current=null;return;}lastTap.current={...end,time:now};}if(model.current.scale===1)apply({scale:1,x:0,y:0});else apply(model.current,true);}
 function zoom(scale){lastTap.current=null;apply({scale:clamp(scale,1,4),x:0,y:0},true);}
 return <div className="u-gallery-viewer" ref={dialog} role="dialog" aria-modal="true" aria-label={(es?'Fotos de ':'Photos of ')+businessName} style={{'--gallery-opacity':view.scale===1?Math.max(.45,1-Math.abs(view.y)/550):1}}><header className="u-gallery-viewer-header"><div><strong>{businessName}</strong><span>{index+1} / {photos.length}</span></div><button className="u-gallery-close" aria-label={es?'Cerrar foto':'Close photo'} onClick={onClose}><Icon name="close" size={19}/></button></header><div className="u-gallery-stage" ref={stage} onPointerDown={down} onPointerMove={drag} onPointerUp={e=>up(e)} onPointerCancel={e=>up(e,true)}><div className="u-gallery-transform" style={{transform:`translate3d(${view.x}px,${view.y}px,0) scale(${view.scale})`}}>{src&&!failed?<img ref={photo} src={src} alt={localized(row,'alt',lang)||localized(row,'caption',lang)||businessName} draggable={false} onError={()=>setFailed(true)}/>:<div className="u-gallery-unavailable"><Icon name="image" size={42}/><p>{es?'Esta foto no está disponible.':'This photo is unavailable.'}</p></div>}</div></div><footer className="u-gallery-viewer-footer">{localized(row,'caption',lang)&&<p>{localized(row,'caption',lang)}</p>}<div className="u-gallery-controls">{photos.length>1&&<button aria-label={es?'Foto anterior':'Previous photo'} onClick={()=>move(-1)}><Icon name="back" size={19}/></button>}<button disabled={view.scale<=1||failed} aria-label={es?'Alejar foto':'Zoom out'} onClick={()=>zoom(view.scale-.5)}>−</button><button className="u-gallery-reset" disabled={failed} aria-label={es?'Restablecer zoom':'Reset zoom'} onClick={()=>zoom(1)}>{Math.round(view.scale*100)}%</button><button disabled={view.scale>=4||failed} aria-label={es?'Acercar foto':'Zoom in'} onClick={()=>zoom(view.scale+.5)}>＋</button>{photos.length>1&&<button aria-label={es?'Siguiente foto':'Next photo'} onClick={()=>move(1)}><Icon name="chevron" size={19}/></button>}</div><small>{es?'Pellizca para ampliar · desliza hacia abajo para cerrar':'Pinch to zoom · swipe down to close'}</small></footer></div>;
}
