'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {localized} from './discovery-model';
import {pointsDisclaimer} from './points-copy';
export default function ServiceBooking({service,business,promotion,live,lang,t,onBooked}){
 const es=lang==='es',tz=business.timezone||'America/Mazatlan',date=d=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d),today=date(new Date()),max=date(new Date(Math.min(Date.now()+90*86400000,promotion?new Date(promotion.ends_at).getTime():Infinity)));
 const [day,setDay]=useState(today),[staff,setStaff]=useState([]),[worker,setWorker]=useState(''),[slots,setSlots]=useState([]),[chosen,setChosen]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[finding,setFinding]=useState(false),[nextMessage,setNextMessage]=useState('');
 const lock=useRef(false),event=useRef(null),search=useRef(0);
 useEffect(()=>{let active=true;supabase.rpc('bookable_staff',{p_service:service.id}).then(({data,error})=>{if(active){setStaff(data||[]);if(error)setError(t.error);}});return()=>{active=false;};},[service.id,t.error]);
 useEffect(()=>{let active=true;++search.current;setFinding(false);setNextMessage('');setLoading(true);setChosen('');setError('');setSlots([]);supabase.rpc(promotion?'promotion_slots':'service_slots',promotion?{p_promotion:promotion.id,p_day:day}:{p_service:service.id,p_day:day,p_collaborator:worker||null}).then(({data,error})=>{if(!active)return;setSlots(error?[]:(data||[]).filter(s=>!worker||s.collaborator_id===worker));if(error)setError(t.error);setLoading(false);});return()=>{active=false;++search.current;};},[day,worker,service.id,promotion?.id,retry,t.error]);
 const slot=slots.find(s=>s.collaborator_id+'|'+s.starts_at===chosen);
 async function nextDay(){const token=++search.current;setFinding(true);setNextMessage('');try{const {data,error}=await supabase.rpc('next_service_day',{p_service:service.id,p_collaborator:worker||null,p_after:day,p_promotion:promotion?.id||null});if(token!==search.current)return;if(error)throw error;if(data&&data<=max)setDay(data);else setNextMessage(es?'No hay más disponibilidad en el período de reserva.':'No further availability in the booking period.');}catch{if(token===search.current)setError(t.error);}finally{if(token===search.current)setFinding(false);}}
 async function book(){if(!slot||lock.current)return;lock.current=true;setBusy(true);setError('');try{let result;if(promotion){const click=await live.attribution(promotion);result=await supabase.rpc('book_promotion',{p_promotion:promotion.id,p_click:click,p_collaborator:slot.collaborator_id,p_start:slot.starts_at});}else{event.current||=crypto.randomUUID();result=await supabase.rpc('book_service',{p_service:service.id,p_collaborator:slot.collaborator_id,p_start:slot.starts_at,p_event:event.current});}if(result.error)throw result.error;const visit=Array.isArray(result.data)?result.data[0]:result.data;if(!visit?.id)throw Error('Missing booking');if(promotion)live.clearAttribution(promotion);onBooked(visit);}catch{setError(es?'No pudimos reservar. Actualiza los horarios e inténtalo de nuevo.':'Could not book. Refresh times and try again.');}finally{lock.current=false;setBusy(false);}}
 function changeDay(value){if(value){event.current=null;setDay(value);}}
 return <section className="u-promo-booking"><span>{business.name}</span><h2>{localized(service,'name',lang)}</h2><p>{localized(service,'description',lang)}</p><strong className="u-promo-price">{new Intl.NumberFormat(es?'es-MX':'en-US',{style:'currency',currency:'MXN'}).format(promotion?promotion.special_price_mxn:service.price_mxn)} · {service.duration_minutes} min</strong>{promotion&&<p>{localized(promotion,'title',lang)}</p>}
 <p className="u-promo-terms">{es?'Cobertura máxima con saldo elegible: ':'Maximum coverage with eligible balance: '}{Math.round(Number(business.points_coverage_rate??.5)*100)}%. {pointsDisclaimer(lang)}</p>
 {staff.some(s=>!s.is_solo)&&<label>{es?'¿Quién te gustaría que te atienda?':'Who would you like to see?'}<select value={worker} disabled={busy} onChange={e=>{event.current=null;setWorker(e.target.value);}}><option value="">{es?'Cualquier integrante disponible':'Any available team member'}</option>{staff.map(s=><option key={s.collaborator_id} value={s.collaborator_id}>{s.collaborator_name}</option>)}</select></label>}
 <label>{es?'Fecha del servicio':'Service date'}<input type="date" value={day} min={today} max={max} disabled={busy} onChange={e=>changeDay(e.target.value)}/></label><small>{es?'Hora local del establecimiento':'Establishment local time'} · {tz}</small>{loading?<p role="status">{t.contentLoading}</p>:<div className="u-promo-slots">{slots.map(s=>{const key=s.collaborator_id+'|'+s.starts_at;return <button key={key} disabled={busy} className={chosen===key?'selected':''} aria-pressed={chosen===key} onClick={()=>{if(chosen!==key)event.current=null;setChosen(key);}}>{new Date(s.starts_at).toLocaleTimeString(es?'es-MX':'en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit'})}<small>{s.collaborator_name}</small></button>;})}</div>}
 {!loading&&!slots.length&&!error&&<div><p>{es?'No hay horarios libres para esta fecha. Puedes elegir otro día o buscar la siguiente disponibilidad.':'No free times on this date. Choose another day or find the next availability.'}</p><button className="u-secondary" disabled={finding||busy} onClick={nextDay}>{finding?t.contentLoading:es?'Buscar siguiente día disponible':'Find next available day'}</button></div>}{nextMessage&&<p role="status">{nextMessage}</p>}{error&&<p role="alert">{error}</p>}<button className="u-text" disabled={loading||busy} onClick={()=>setRetry(x=>x+1)}>{es?'Actualizar horarios':'Refresh times'}</button><button className="u-primary" disabled={!slot||busy||loading} onClick={book}>{busy?t.contentLoading:es?'Confirmar reserva':'Confirm booking'}</button>{promotion&&<p className="u-promo-terms">{localized(promotion,'terms',lang)}</p>}</section>;
}
