'use client';
export const emptyWeek=()=>Array.from({length:7},(_,weekday)=>({weekday,enabled:false,intervals:[]}));
export const dayNames=lang=>lang==='es'?['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado']:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export function normalizeWeek(value){return emptyWeek().map(row=>({...row,...(value||[]).find(d=>Number(d.weekday)===row.weekday)}));}
export function hoursFromRows(rows){return emptyWeek().map(day=>({...day,enabled:rows.some(r=>Number(r.weekday)===day.weekday),intervals:rows.filter(r=>Number(r.weekday)===day.weekday).sort((a,b)=>a.opens_at.localeCompare(b.opens_at)).map(r=>({opens_at:r.opens_at.slice(0,5),closes_at:r.closes_at.slice(0,5)}))}));}
export function scheduleText(value,lang){return [...normalizeWeek(value)].sort((a,b)=>(a.weekday||7)-(b.weekday||7)).map(d=>dayNames(lang)[d.weekday]+': '+(d.enabled&&d.intervals.length?d.intervals.map(x=>x.opens_at+'–'+x.closes_at).join(', '):lang==='es'?'Cerrado':'Closed')).join('\n');}
export function validWeek(value){const week=normalizeWeek(value);return week.every(d=>!d.enabled||d.intervals.length>0&&d.intervals.every(x=>/^\d{2}:\d{2}$/.test(x.opens_at)&&/^\d{2}:\d{2}$/.test(x.closes_at)&&x.opens_at<x.closes_at)&&[...d.intervals].sort((a,b)=>a.opens_at.localeCompare(b.opens_at)).every((x,i,rows)=>i===0||x.opens_at>=rows[i-1].closes_at));}
export default function WeeklyHours({value,onChange,lang,disabled=false}){
 const es=lang==='es',week=normalizeWeek(value),days=dayNames(lang);function update(weekday,patch){onChange(week.map(d=>d.weekday===weekday?{...d,...patch}:d));}
 return <div className="weekly-hours">{[1,2,3,4,5,6,0].map(weekday=>{const day=week[weekday];return <section className="weekly-day" key={weekday}><div className="weekly-day-head"><strong>{days[weekday]}</strong><button type="button" className={'hours-switch'+(day.enabled?' on':'')} role="switch" aria-checked={day.enabled} aria-label={days[weekday]} disabled={disabled} onClick={()=>update(weekday,{enabled:!day.enabled,intervals:!day.enabled&&!day.intervals.length?[{opens_at:'09:00',closes_at:'18:00'}]:day.intervals})}><span>{day.enabled?(es?'Activo':'Open'):(es?'Cerrado':'Closed')}</span><i/></button></div>{day.enabled&&<>{day.intervals.map((interval,i)=><div className="weekly-interval" key={i}><label><span>{es?'Desde':'From'}</span><input type="time" aria-label={`${days[weekday]} · ${es?'Desde':'From'} ${i+1}`} value={interval.opens_at} disabled={disabled} onChange={e=>update(weekday,{intervals:day.intervals.map((x,j)=>j===i?{...x,opens_at:e.target.value}:x)})}/></label><label><span>{es?'Hasta':'Until'}</span><input type="time" aria-label={`${days[weekday]} · ${es?'Hasta':'Until'} ${i+1}`} value={interval.closes_at} disabled={disabled} onChange={e=>update(weekday,{intervals:day.intervals.map((x,j)=>j===i?{...x,closes_at:e.target.value}:x)})}/></label><button type="button" className="quiet" disabled={disabled} aria-label={(es?'Quitar tramo de ':'Remove interval for ')+days[weekday]+' '+(i+1)} onClick={()=>update(weekday,{intervals:day.intervals.filter((_,j)=>j!==i)})}>×</button></div>)}<button type="button" className="text-button hours-add" disabled={disabled||day.intervals.length>=6} onClick={()=>update(weekday,{intervals:[...day.intervals,{opens_at:'',closes_at:''}]})}>＋ {es?'Agregar tramo':'Add interval'}</button></>}</section>})}{!validWeek(week)&&<p role="alert">{es?'Completa los tramos activos; el final debe ser posterior al inicio y los horarios no pueden cruzarse.':'Complete open intervals; closing must be after opening and times cannot overlap.'}</p>}</div>;
}
