begin;
create temp table wf(u uuid,u2 uuid,m uuid,other uuid,b uuid,b2 uuid,s uuid,seed uuid,v uuid,appt uuid,p uuid,p2 uuid,code text);
insert into wf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null,null,null);grant all on wf to authenticated;
insert into auth.users(id,email) select u,'qa-wallet-'||u||'@example.invalid' from wf union all select u2,'qa-wallet-'||u2||'@example.invalid' from wf union all select m,'qa-wallet-'||m||'@example.invalid' from wf union all select other,'qa-wallet-'||other||'@example.invalid' from wf;
insert into public.profiles(user_id,live_enabled) select u,true from wf;
insert into public.businesses(id,slug,name,status,enrollment_status,booking_enabled,category_id) select b,'qa-'||b,'QA Walk In','published','active',true,(select id from public.categories limit 1) from wf union all select b2,'qa-'||b2,'QA Affiliated','published','active',true,(select id from public.categories limit 1) from wf;
insert into public.business_members(business_id,user_id,role) select b,m,'owner' from wf union all select b2,other,'owner' from wf;
insert into public.services(id,business_id,name,name_es,name_en,duration_minutes,price_mxn) select s,b,'QA Service','Servicio QA','QA Service',30,1000 from wf;
insert into public.visits(id,business_id,customer_id,kind,source,status,starts_at,ends_at,amount_mxn,completed_at) select seed,b,u,'walk_in','business','completed',now()-interval '2 days',now()-interval '2 days'+interval '1 hour',10000,now()-interval '2 days' from wf;
insert into public.customer_relationships(business_id,customer_id,first_visit_id) select b,u,seed from wf;
insert into public.reward_ledger(business_id,visit_id,customer_id,base_mxn,rate,credit_mxn) select b,seed,u,10000,.1,1000 from wf;
insert into public.visits(id,business_id,customer_id,service_id,kind,source,status,starts_at,ends_at,booked_price_mxn) select gen_random_uuid(),b,u,s,'appointment','mi_espacio','scheduled',now()-interval '1 hour',now()+interval '1 hour',1000 from wf returning id;
update wf set appt=(select id from public.visits where business_id=wf.b and kind='appointment');
set local role authenticated;select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
do $$declare f wf;begin select * into f from wf;
 perform public.save_business_benefits(f.b,false,.20);
 if (select coverage_rate_snapshot from public.visits where id=f.appt)<>.50 then raise exception 'Existing booking lost protection';end if;
 begin perform public.save_business_benefits(f.b,false,.25);raise exception 'Unsupported tier';exception when raise_exception then if sqlerrm='Unsupported tier' then raise;end if;end;
 if exists(select 1 from public.service_slots(f.s,(now() at time zone 'America/Mazatlan')::date)) then raise exception 'Walk-in business still accepts slots';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from wf;
do $$declare f wf;v public.visits;t jsonb;begin select * into f from wf;
 v=public.register_walk_in(f.b,gen_random_uuid());if v.source<>'business' or v.arrival_origin<>'spontaneous' or v.coverage_rate_snapshot is not null then raise exception 'Spontaneous attributed to ad/protected';end if;
 if (public.register_walk_in(f.b,v.booking_event_id)).id<>v.id then raise exception 'Retry duplicated visit';end if;
 begin perform public.register_walk_in(f.b,gen_random_uuid());raise exception 'Duplicate open walkin';exception when raise_exception then if sqlerrm='Duplicate open walkin' then raise;end if;end;
 t=public.customer_presence(v.id);update wf set v=v.id,code=t->>'code';
 if exists(select 1 from public.reward_ledger where visit_id=v.id) then raise exception 'Arrival earned points';end if;
 begin perform public.prepare_visit_payment(v.id,1000);raise exception 'Customer priced invoice';exception when raise_exception then if sqlerrm='Customer priced invoice' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',other,'role','authenticated')::text,true) from wf;
do $$declare f wf;begin select * into f from wf;
 begin perform public.verify_presence(f.b,f.code);raise exception 'Foreign merchant presence';exception when raise_exception then if sqlerrm='Foreign merchant presence' then raise;end if;end;
 if exists(select 1 from public.visit_payments where visit_id=f.v) then raise exception 'Foreign payment leaked';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
do $$declare f wf;p public.visit_payments;begin select * into f from wf;
 begin perform public.prepare_visit_payment(f.v,1000);raise exception 'Missing presence accepted';exception when raise_exception then if sqlerrm='Missing presence accepted' then raise;end if;end;
 if (public.verify_presence(f.b,f.code)).id<>f.v then raise exception 'Presence not verified';end if;
 p=public.prepare_visit_payment(f.v,1000);update wf set p=p.id;
 begin perform public.settle_visit_payment(p.id);raise exception 'No customer consent';exception when raise_exception then if sqlerrm='No customer consent' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from wf;
do $$declare f wf;p public.visit_payments;w jsonb;begin select * into f from wf;p=(select row from public.visit_payments row where id=f.p);
 begin perform public.confirm_visit_payment(f.p,201,p.policy_version);raise exception 'Cap exceeded';exception when raise_exception then if sqlerrm='Cap exceeded' then raise;end if;end;
 p=public.confirm_visit_payment(f.p,200,p.policy_version);if (public.confirm_visit_payment(f.p,200,p.policy_version)).id<>p.id then raise exception 'Duplicate confirmation';end if;
 w=public.wallet_summary();if (w->>'available_mxn')::numeric<>800 or (w->>'held_mxn')::numeric<>200 then raise exception 'No wallet hold';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
do $$declare f wf;r jsonb;begin select * into f from wf;
 perform public.save_business_benefits(f.b,false,.30);r=public.settle_visit_payment(f.p);if r->>'state'<>'needs_confirmation' then raise exception 'Changed walkin settled silently';end if;update wf set p2=(r->'payment'->>'id')::uuid;
 if exists(select 1 from public.reward_ledger where visit_id=f.v) then raise exception 'Changed policy rewarded';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from wf;
do $$declare f wf;p public.visit_payments;begin select * into f from wf;p=(select row from public.visit_payments row where id=f.p2);
 if (public.wallet_summary()->>'available_mxn')::numeric<>1000 then raise exception 'Old hold not released';end if;
 perform public.confirm_visit_payment(p.id,300,p.policy_version);
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
do $$declare f wf;r jsonb;begin select * into f from wf;r=public.settle_visit_payment(f.p2);perform public.settle_visit_payment(f.p2);
 if (select count(*) from public.reward_ledger where visit_id=f.v)<>1 or (select credit_mxn from public.reward_ledger where visit_id=f.v)<>70 then raise exception 'Reward duplicated or calculated on points';end if;
 if (select points_mxn from public.visit_payments where id=f.p2)<>300 then raise exception 'Redemption not recorded';end if;
 if (select count(*) from public.fee_ledger where visit_id=f.v)<>0 then raise exception 'Repeat spontaneous incorrectly usage attributed';end if;
end $$;
-- A protected appointment keeps 50% even after the current policy decreases.
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from wf;
update wf set code=public.customer_presence(appt)->>'code';
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
select public.verify_presence(b,code) from wf;
update wf set p=(public.prepare_visit_payment(appt,1000)).id;
select public.save_business_benefits(b,false,.20) from wf;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from wf;
select public.confirm_visit_payment(p,500,(select policy_version from public.visit_payments where id=wf.p)) from wf;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
select public.settle_visit_payment(p) from wf;
do $$declare f wf;begin select * into f from wf;if (select coverage_rate from public.visit_payments where id=f.p)<>.50 or (select count(*) from public.fee_ledger where visit_id=f.appt)<>1 then raise exception 'Protected booking or attribution lost';end if;end $$;
-- Contact tokens and financial mutation are inaccessible to another customer.
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from wf;
do $$declare f wf;begin select * into f from wf;
 if exists(select 1 from public.visit_payments where customer_id=f.u) or exists(select 1 from public.point_allocations where customer_id=f.u) then raise exception 'Other wallet data leaked';end if;
 begin perform public.customer_presence(f.appt);raise exception 'Foreign token';exception when raise_exception then if sqlerrm='Foreign token' then raise;end if;end;
 begin insert into public.point_allocations(payment_id,customer_id,reward_id,amount_mxn) select f.p,f.u,id,1 from public.reward_ledger limit 1;raise exception 'Direct ledger write';exception when insufficient_privilege then null;end;
end $$;
reset role;
-- An unrelated wallet origin is eligible only through a defined category affinity,
-- and can never cover more than 20%, even when the merchant authorizes 50%.
insert into public.visits(id,business_id,customer_id,kind,source,status,starts_at,ends_at,amount_mxn,completed_at)
 select gen_random_uuid(),b2,u2,'walk_in','business','completed',now()-interval '3 days',now()-interval '3 days'+interval '1 hour',10000,now()-interval '3 days' from wf;
insert into public.reward_ledger(business_id,visit_id,customer_id,base_mxn,rate,credit_mxn)
 select b2,(select id from public.visits where business_id=wf.b2 and customer_id=wf.u2),u2,10000,.1,1000 from wf;
insert into public.profiles(user_id,live_enabled) select u2,true from wf;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
select public.save_business_benefits(b,false,.50) from wf;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from wf;
do $$declare f wf;v public.visits;events jsonb;click uuid;event uuid=gen_random_uuid();begin select * into f from wf;
 events=public.live_benefits();if not exists(select 1 from jsonb_array_elements(events) x where x->>'business_id'=f.b::text and (x->>'coverage_rate')::numeric=.50) then raise exception 'Increase not announced';end if;
 select (x->>'id')::uuid into click from jsonb_array_elements(events) x where x->>'business_id'=f.b::text;
 if public.record_benefit_click(click,event,'capsule')<>public.record_benefit_click(click,event,'capsule') then raise exception 'Click retry duplicated';end if;
 v=public.register_walk_in(f.b,gen_random_uuid());update wf set v=v.id,code=public.customer_presence(v.id)->>'code';end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
select public.verify_presence(b,code) from wf;
update wf set p=(public.prepare_visit_payment(v,1000)).id;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from wf;
do $$declare f wf;p public.visit_payments;begin select * into f from wf;select * into p from public.visit_payments where id=f.p;
 if (public.visit_checkout(f.v)->'budget'->>'max_points_mxn')::numeric<>200 then raise exception 'Affiliated coverage exceeds twenty percent';end if;
 begin perform public.confirm_visit_payment(p.id,201,p.policy_version);raise exception 'Affiliated overspend allowed';exception when raise_exception then if sqlerrm='Affiliated overspend allowed' then raise;end if;end;
 perform public.confirm_visit_payment(p.id,200,p.policy_version);
 if (public.wallet_summary()->>'available_mxn')::numeric<>800 then raise exception 'Affiliated hold missing';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from wf;
select public.save_business_benefits(b,false,.20) from wf;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from wf;
do $$declare f wf;begin select * into f from wf;
 if exists(select 1 from jsonb_array_elements(public.live_benefits()) x where x->>'business_id'=f.b::text) then raise exception 'Decrease or stale increase announced';end if;
 update public.profiles set live_enabled=false where user_id=f.u2;
 if public.live_benefits()<>'[]'::jsonb then raise exception 'Live opt-out ignored';end if;
end $$;
reset role;
select 'PASS: optional reservations, spontaneous attribution, presence proof, customer consent, tier limits, wallet holds/release, policy changes require reconfirmation, protected appointments, net-cash rewards, idempotency, private financial data' result;
rollback;
