begin;
create temp table sf(u uuid,m uuid,b uuid,s1 uuid,s2 uuid,c uuid,ana uuid,bea uuid,w uuid,v uuid,d date,start timestamptz,week jsonb);
insert into sf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null,null,null,(now() at time zone 'America/Mazatlan')::date+1,null,null);grant all on sf to authenticated;
insert into auth.users(id,email) select u,'qa-booking-'||u||'@example.invalid' from sf union all select m,'qa-booking-'||m||'@example.invalid' from sf;
insert into public.businesses(id,slug,name,status,enrollment_status,booking_enabled) select b,'qa-'||b,'QA Schedule','published','active',true from sf;
insert into public.business_members(business_id,user_id,role) select b,m,'owner' from sf;
insert into public.services(id,business_id,name,name_es,name_en,duration_minutes,price_mxn) select s1,b,'Manicure','Manicure','Manicure',60,500 from sf union all select s2,b,'Pedicure','Pedicure','Pedicure',30,300 from sf;
update sf set week=(select jsonb_agg(jsonb_build_object('weekday',day,'enabled',day=extract(dow from sf.d)::int,'intervals',case when day=extract(dow from sf.d)::int then '[{"opens_at":"09:00","closes_at":"13:00"},{"opens_at":"15:00","closes_at":"18:00"}]'::jsonb else '[]'::jsonb end)) from generate_series(0,6) day);
set local role authenticated;select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from sf;
do $$declare f sf;begin select * into f from sf;perform public.save_business_hours(f.b,f.week);update sf set c=(select id from public.collaborators where business_id=f.b and is_solo);
 begin perform public.save_business_hours(f.b,jsonb_set(f.week,array[extract(dow from f.d)::int::text,'intervals'],'[{"opens_at":"09:00","closes_at":"13:00"},{"opens_at":"12:00","closes_at":"16:00"}]'));raise exception 'Overlapping opening intervals accepted';exception when raise_exception then if sqlerrm='Overlapping opening intervals accepted' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from sf;
do $$declare f sf;v public.visits;begin select * into f from sf;
 if exists(select 1 from public.service_slots(f.s1,f.d) where (starts_at at time zone 'America/Mazatlan')::time>='12:15' and (starts_at at time zone 'America/Mazatlan')::time<'15:00') then raise exception 'Lunch break leaked';end if;
 if (select count(*) from public.bookable_staff(f.s1))<>1 then raise exception 'No individual capacity';end if;
 v=public.book_service(f.s1,f.c,(f.d+'09:00'::time) at time zone 'America/Mazatlan',gen_random_uuid());update sf set v=v.id;
 if (public.book_service(f.s1,f.c,v.starts_at,v.booking_event_id)).id<>v.id then raise exception 'Booking retry duplicate';end if;
 begin perform public.book_service(f.s2,f.c,v.starts_at,gen_random_uuid());raise exception 'Solo overlap across services';exception when raise_exception then if sqlerrm='Solo overlap across services' then raise;end if;end;
 if exists(select 1 from public.service_slots(f.s2,f.d) where starts_at>=v.starts_at and starts_at<v.ends_at) then raise exception 'Solo busy slots visible';end if;
 if exists(select 1 from public.workers) then raise exception 'Worker contacts exposed';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from sf;
do $$declare f sf;c public.collaborators;own jsonb;begin select * into f from sf;
 own=jsonb_set(f.week,array[extract(dow from f.d)::int::text,'intervals'],'[{"opens_at":"11:00","closes_at":"12:00"},{"opens_at":"15:00","closes_at":"16:00"}]');
 c=public.save_team_member(f.b,null,jsonb_build_object('name','Ana','email','ana-'||f.b||'@example.invalid','phone','6241234567','inherits_business_hours',false,'opening_schedule',own),array[f.s1,f.s2]);update sf set ana=c.id,w=c.worker_id;
 c=public.save_team_member(f.b,null,jsonb_build_object('name','Bea','email','bea-'||f.b||'@example.invalid','phone','6241234568'),array[f.s1]);update sf set bea=c.id;
 if (select count(*) from public.worker_service_stats where worker_id=(select w from sf))<>2 then raise exception 'Ana skills missing';end if;
 begin perform public.save_team_member(f.b,null,'{"name":"Incomplete"}',array[f.s1]);raise exception 'Worker contact not required';exception when raise_exception then if sqlerrm='Worker contact not required' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from sf;
do $$declare f sf;v public.visits;t timestamptz;begin select * into f from sf;t=(f.d+'11:00'::time) at time zone 'America/Mazatlan';
 if (select count(*) from public.bookable_staff(f.s2))<>1 then raise exception 'Unqualified staff offered';end if;
 if exists(select 1 from public.service_slots(f.s2,f.d) where collaborator_id<>f.ana or (starts_at at time zone 'America/Mazatlan')::time<'11:00') then raise exception 'Worker hours or skill ignored';end if;
 begin perform public.book_service(f.s2,f.bea,t,gen_random_uuid());raise exception 'Unqualified worker booked';exception when raise_exception then if sqlerrm='Unqualified worker booked' then raise;end if;end;
 v=public.book_service(f.s2,f.ana,t,gen_random_uuid());update sf set v=v.id,start=t;
 if v.worker_id<>f.w or v.service_name_es<>'Pedicure' then raise exception 'Worker snapshot missing';end if;
 begin perform public.book_service(f.s1,f.ana,t,gen_random_uuid());raise exception 'Same worker simultaneous services';exception when raise_exception then if sqlerrm='Same worker simultaneous services' then raise;end if;end;
 perform public.book_service(f.s1,f.bea,t,gen_random_uuid());
 if public.next_service_day(f.s2,f.ana,f.d,null)<>f.d then raise exception 'Next worker day failed';end if;
 if exists(select 1 from public.worker_service_stats) or exists(select 1 from public.workers) then raise exception 'Worker curriculum or contacts leaked';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from sf;
do $$declare f sf;own jsonb;begin select * into f from sf;
 own=jsonb_set(f.week,array[extract(dow from f.d)::int::text,'intervals'],'[{"opens_at":"15:30","closes_at":"16:00"}]');perform public.save_service_hours(f.s2,false,own);
 begin perform public.save_team_member(f.b,f.ana,jsonb_build_object('name','Ana','email','ana-'||f.b||'@example.invalid','phone','6241234567','active',false),array[f.s1,f.s2]);raise exception 'Archived busy worker';exception when raise_exception then if sqlerrm='Archived busy worker' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from sf;
do $$declare f sf;begin select * into f from sf;
 if (select count(*) from public.service_slots(f.s2,f.d,f.ana))<>1 or not exists(select 1 from public.service_slots(f.s2,f.d,f.ana) where (starts_at at time zone 'America/Mazatlan')::time='15:30') then raise exception 'Service override ignored';end if;
end $$;
reset role;
update public.visits set starts_at=now()-interval '2 hours',ends_at=now()-interval '90 minutes' where id=(select v from sf);
set local role authenticated;select set_config('request.jwt.claims',json_build_object('sub',m,'role','authenticated')::text,true) from sf;
do $$declare f sf;begin select * into f from sf;perform public.complete_service_visit(f.v,300);perform public.complete_service_visit(f.v,300);
 if (select completed_services from public.worker_service_stats where worker_id=f.w and service_id=f.s2)<>1 then raise exception 'Completed worker activity counted incorrectly';end if;
 perform public.save_team_member(f.b,f.ana,jsonb_build_object('name','Ana','email','ana-'||f.b||'@example.invalid','phone','6241234567'),array[f.s1]);
 if (select completed_services from public.worker_service_stats where worker_id=f.w and service_id=f.s2)<>1 then raise exception 'Removing assignment erased curriculum';end if;
end $$;
reset role;select 'PASS: business breaks, solo capacity, cross-service collisions, staff qualification and schedules, simultaneous different workers, service override, ID/contact privacy and durable completed activity' result;rollback;
