begin;
create temp table vfixtures(u uuid,u2 uuid,a uuid,b uuid,hidden uuid,r uuid,r2 uuid,newr uuid,slot timestamptz,slot2 timestamptz);
insert into vfixtures values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null,null,null);
grant all on vfixtures to authenticated;
insert into auth.users(id,email,email_confirmed_at) select u,'qa-intake-'||u||'@example.invalid',now() from vfixtures union all select u2,'qa-intake-'||u2||'@example.invalid',now() from vfixtures union all select a,'qa-admin-'||a||'@example.invalid',now() from vfixtures;
insert into public.platform_admins(user_id) select a from vfixtures;
insert into public.businesses(id,slug,name,directory_listed) select b,'qa-'||b,'QA Claimable',true from vfixtures union all select hidden,'qa-'||hidden,'QA Private Draft',false from vfixtures;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from vfixtures;
do $$declare f vfixtures;q public.business_intake_requests;t record;n public.business_intake_requests;begin select * into f from vfixtures;
 if (select count(*) from public.businesses where id=f.hidden)<>0 then raise exception 'Private draft leaked';end if;
 insert into public.favorites(customer_id,business_id) values(f.u,f.b);
 begin insert into public.favorites(customer_id,business_id) values(f.u,f.hidden);raise exception 'Private favorite accepted';exception when insufficient_privilege then null;end;
 begin insert into public.favorites(customer_id,business_id) values(f.u2,f.b);raise exception 'Foreign favorite accepted';exception when insufficient_privilege then null;end;
 begin perform public.business_favorite_count(f.b);raise exception 'Count exposed to unverified customer';exception when raise_exception then if sqlerrm='Count exposed to unverified customer' then raise;end if;end;
 q=public.save_business_intake(null,f.b,'{}');
 if q.kind<>'existing' or q.user_id<>f.u then raise exception 'Bad claim';end if;
 if (public.save_business_intake(q.id,null,'{"name":"Tampered"}')).draft<>'{}'::jsonb then raise exception 'Existing business editable';end if;
 update public.businesses set name='Tampered' where id=f.b;
 if exists(select 1 from public.businesses where id=f.b and name='Tampered') then raise exception 'Unverified customer edited business';end if;
 begin insert into public.business_members(business_id,user_id,role) values(f.b,f.u,'owner');raise exception 'Self assignment';exception when insufficient_privilege then null;end;
 select * into t from public.verification_slots() where extract(hour from starts_at at time zone 'America/Mazatlan')=11 order by starts_at limit 1;
 if t.starts_at is null or t.ends_at-t.starts_at<>interval '2 hours' or (t.starts_at at time zone 'America/Mazatlan')::date>(now() at time zone 'America/Mazatlan')::date+3 or extract(hour from t.starts_at at time zone 'America/Mazatlan') not between 10 and 18 then raise exception 'Bad initial slots';end if;
 q=public.book_verification(q.id,t.starts_at,'QA owner','');
 if (public.book_verification(q.id,t.starts_at,'QA owner','')).id<>q.id then raise exception 'Duplicate booking';end if;
 if exists(select 1 from public.verification_slots() where starts_at=t.starts_at) then raise exception 'Reserved slot visible';end if;
 if exists(select 1 from public.verification_slots() where starts_at=t.starts_at+interval '1 hour') or not exists(select 1 from public.verification_slots() where starts_at=t.starts_at+interval '2 hours') then raise exception '11:00 must block 12:00 and allow 13:00';end if;
 begin perform public.save_business_intake(q.id,null,'{}');raise exception 'Submitted request edited';exception when raise_exception then if sqlerrm='Submitted request edited' then raise;end if;end;
 n=public.save_business_intake(null,null,'{"name":"","address":"","opening_hours_es":""}');
 begin perform public.book_verification(n.id,t.starts_at,'QA owner','');raise exception 'Missing basics accepted';exception when raise_exception then if sqlerrm='Missing basics accepted' then raise;end if;end;
 n=public.save_business_intake(n.id,null,'{"name":"QA New","address":"QA Street 100 Los Cabos","opening_hours_es":"Lunes a domingo 10-20","gallery":[{"image_url":"https://example.invalid/a.jpg","caption_es":"Foto","caption_en":"Photo"}],"services":[{"name_es":"Masaje","price_mxn":"500","duration_minutes":"30"},{"name_es":"Servicio incompleto"}],"team":[{"name":"QA Team","availability":[{"weekday":"1","opens_at":"10:00","closes_at":"18:00"}]}]}');
 select * into t from public.verification_slots() order by starts_at limit 1;
 n=public.book_verification(n.id,t.starts_at,'QA owner','');
 update vfixtures set r=q.id,newr=n.id,slot=q.starts_at,slot2=n.starts_at;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from vfixtures;
do $$declare f vfixtures;q public.business_intake_requests;begin select * into f from vfixtures;
 if exists(select 1 from public.business_intake_requests where id=f.r) then raise exception 'Other request leaked';end if;
 begin perform public.save_business_intake(f.newr,null,'{}');raise exception 'Other draft edited';exception when raise_exception then if sqlerrm='Other draft edited' then raise;end if;end;
 begin perform public.admin_verification(f.r,'approved','','','');raise exception 'Self approval';exception when raise_exception then if sqlerrm='Self approval' then raise;end if;end;
 q=public.save_business_intake(null,f.b,'{}');
 begin perform public.book_verification(q.id,f.slot,'Other owner','');raise exception 'Double booking';exception when raise_exception then if sqlerrm='Double booking' then raise;end if;end;
 if exists(select 1 from public.business_intake_requests where id=q.id and status<>'draft') then raise exception 'Failed booking changed request';end if;
 update vfixtures set r2=q.id;
end $$;
-- Move fixtures into the past to exercise actual admin visit verification, without waiting.
reset role;
update public.business_intake_requests set starts_at=now()-interval '6 hours',ends_at=now()-interval '4 hours' where id=(select r from vfixtures);
update public.business_intake_requests set starts_at=now()-interval '4 hours',ends_at=now()-interval '2 hours' where id=(select newr from vfixtures);
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',a,'role','authenticated')::text,true) from vfixtures;
do $$declare f vfixtures;q public.business_intake_requests;begin select * into f from vfixtures;
 if public.business_favorite_count(f.b)<>1 then raise exception 'Wrong interest count';end if;
 begin perform public.admin_verification(f.r,'approved','','','');raise exception 'Approval before visit';exception when raise_exception then if sqlerrm='Approval before visit' then raise;end if;end;
 perform public.admin_verification(f.r,'confirmed','Confirmed','','');
 perform public.admin_verification(f.r,'visited','Visit completed','','');
 q=public.admin_verification(f.r,'approved','Verified owner','Tu negocio es tuyo','Your business is yours');
 if not exists(select 1 from public.business_members where business_id=f.b and user_id=f.u and role='owner') then raise exception 'Owner not assigned';end if;
 perform public.admin_verification(f.newr,'visited','Visit completed','','');
 q=public.admin_verification(f.newr,'approved','Verified','','');
 if q.business_id is null or not exists(select 1 from public.businesses where id=q.business_id and status='draft' and not booking_enabled and not directory_listed) then raise exception 'New business auto-published';end if;
 if (select count(*) from public.services where business_id=q.business_id)<>1 or exists(select 1 from public.services where business_id=q.business_id and active) then raise exception 'Bad service import';end if;
 if (select count(*) from public.business_gallery where business_id=q.business_id)<>1 or (select count(*) from public.availability where business_id=q.business_id)<>1 then raise exception 'Missing photos/team';end if;
 begin perform public.admin_verification(f.r2,'visited','','','');raise exception 'Draft marked visited';exception when raise_exception then if sqlerrm='Draft marked visited' then raise;end if;end;
end $$;
-- Fill the entire first window and assert expansion in increments of two calendar days.
reset role;
insert into public.verification_blocks(starts_at,ends_at,reason) values(now(),((now() at time zone 'America/Mazatlan')::date+4)::timestamp at time zone 'America/Mazatlan','QA full first window');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from vfixtures;
do $$declare first_day date;last_day date;begin
 select min((starts_at at time zone 'America/Mazatlan')::date),max((starts_at at time zone 'America/Mazatlan')::date) into first_day,last_day from public.verification_slots();
 if first_day<>(now() at time zone 'America/Mazatlan')::date+4 or last_day<>(now() at time zone 'America/Mazatlan')::date+5 then raise exception 'Window did not expand by two days: %, %',first_day,last_day;end if;
end $$;
reset role;
insert into public.verification_blocks(starts_at,ends_at,reason) values(((now() at time zone 'America/Mazatlan')::date+4)::timestamp at time zone 'America/Mazatlan',((now() at time zone 'America/Mazatlan')::date+6)::timestamp at time zone 'America/Mazatlan','QA full expanded window');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from vfixtures;
do $$declare f vfixtures;t record;q public.business_intake_requests;begin select * into f from vfixtures;
 if (select max((starts_at at time zone 'America/Mazatlan')::date) from public.verification_slots())<>(now() at time zone 'America/Mazatlan')::date+7 then raise exception 'Second extension failed';end if;
 select * into t from public.verification_slots() limit 1;
 q=public.book_verification(f.r2,t.starts_at,'Other owner','');
 q=public.cancel_verification(q.id);
 if not exists(select 1 from public.verification_slots() where starts_at=t.starts_at) then raise exception 'Canceled slot not released';end if;
 if exists(select 1 from public.verification_events) then raise exception 'Internal notes leaked';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from vfixtures;
do $$declare f vfixtures;begin select * into f from vfixtures;if public.business_favorite_count(f.b)<>1 then raise exception 'Verified merchant count wrong';end if;end $$;
reset role;
select 'PASS: private drafts, existing locked, ownership only after visit, idempotency, collision prevention, two-hour spacing, calendar horizon +2 +2, cancellation, import and inactive favorites' as verification;
rollback;
