begin;
create temp table qa(u uuid,a uuid,b uuid,v uuid,r uuid,p uuid,f uuid,t timestamptz);
insert into qa values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null);
grant all on qa to authenticated;
insert into auth.users(id,email) select u,'qa-'||u||'@example.invalid' from qa union all select a,'qa-'||a||'@example.invalid' from qa;
insert into public.platform_admins(user_id) select a from qa;
insert into public.profiles(user_id) select u from qa;
insert into public.businesses(id,slug,name,status,enrollment_status,booking_enabled,category_id) select b,'qa-'||b,'QA rollback','published','active',true,(select id from public.categories limit 1) from qa;
insert into public.visits(id,business_id,customer_id,kind,source,status,starts_at,ends_at) select v,b,u,'walk_in','business','checked_in',now(),now()+interval '1 hour' from qa;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from qa;
do $$declare x qa;begin select * into x from qa;
 begin perform public.submit_feedback(x.v,'stars',5,null,'QA');raise exception 'TEST_UNPAID_ALLOWED';exception when others then if sqlerrm not like '%COMPLETED_PAYMENT_REQUIRED%' then raise;end if;end;
end $$;
reset role;
update public.visits set status='completed',completed_at=now() where id=(select v from qa);
insert into public.visit_payments(visit_id,business_id,customer_id,amount_mxn,coverage_rate,policy_version,protected,state,completed_at) select v,b,u,100,.2,1,false,'completed',now() from qa;
set local role authenticated;
update qa set f=public.submit_feedback(v,'diamonds',4,null,'Comentario QA');
do $$declare x qa;begin select * into x from qa;
 begin perform public.submit_feedback(x.v,'stars',1,null,'Duplicate');raise exception 'TEST_DUPLICATE_ALLOWED';exception when others then if sqlerrm not like '%ALREADY_RATED%' then raise;end if;end;
 if exists(select 1 from public.public_feedback(x.b) where id=x.f) then raise exception 'PENDING_LEAK';end if;
 perform public.set_interests(array(select id from public.categories where active limit 5));
 if (select count(*) from public.user_interests where user_id=x.u)<>5 then raise exception 'INTERESTS_FAILED';end if;
 begin perform public.set_interests(array(select id from public.categories where active limit 6));raise exception 'SIX_ALLOWED';exception when others then if sqlerrm not like '%one to five%' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',a,'role','authenticated')::text,true) from qa;
do $$declare x qa;begin select * into x from qa;
 begin perform public.submit_feedback(x.v,'stars',1,null,'Attack');raise exception 'OTHER_CUSTOMER_ALLOWED';exception when others then if sqlerrm not like '%ACCESS_DENIED%' then raise;end if;end;
 perform public.moderate_feedback(x.f,'approved');
 if not exists(select 1 from public.public_feedback(x.b) where id=x.f) then raise exception 'APPROVED_MISSING';end if;
 perform public.moderate_feedback(x.f,'archived');
 if exists(select 1 from public.public_feedback(x.b) where id=x.f) then raise exception 'ARCHIVE_LEAK';end if;
 if not exists(select 1 from public.feedback_summary() where business_id=x.b and diamonds=4) then raise exception 'ARCHIVE_CHANGED_SCORE';end if;
end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from qa;
update qa set t=(select starts_at from public.verification_slots() limit 1);
insert into public.business_intake_requests(id,user_id,contact_email,kind,draft,status,starts_at,ends_at) select r,u,'qa@example.invalid','new','{"name":"QA rollback"}','scheduled',t,t+interval '2 hours' from qa;
update public.business_intake_requests set public_message_es='QA mensaje' where id=(select r from qa);
set local role authenticated;
do $$declare x qa;begin select * into x from qa;
 if not exists(select 1 from public.business_intake_requests where id=x.r and message_version=1 and message_read_version=0) then raise exception 'UNREAD_MISSING';end if;
 perform public.read_intake_message(x.r,1);
 if not exists(select 1 from public.business_intake_requests where id=x.r and message_read_version=1) then raise exception 'READ_FAILED';end if;
 update qa set p=public.propose_verification(r,(select starts_at from public.verification_slots() limit 1),'QA reagendar',false);
 select * into x from qa;
 if not exists(select 1 from public.business_intake_requests where id=x.r and starts_at=x.t) then raise exception 'OLD_SLOT_CHANGED';end if;
 begin perform public.respond_verification(x.p,true,false);raise exception 'SELF_ACCEPT_ALLOWED';exception when others then if sqlerrm not like '%OTHER_PARTY_REQUIRED%' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',a,'role','authenticated')::text,true) from qa;
select public.respond_verification(p,true,true) from qa;
do $$declare x qa;begin select * into x from qa;
 if not exists(select 1 from public.business_intake_requests where id=x.r and starts_at<>x.t and status='confirmed') then raise exception 'ACCEPTANCE_FAILED';end if;
end $$;
select 'PASS: paid-only, ownership, duplicate rejection, moderation, archived averages, five interests, receipts, bilateral rescheduling' as result;
rollback;
