begin;
create temp table fixtures(u uuid,u2 uuid,merchant uuid,foreign_merchant uuid,b uuid,s uuid,c uuid,p uuid,pfuture uuid,click uuid,click2 uuid,v uuid,start_at timestamptz);
insert into fixtures values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null);
grant all on fixtures to authenticated;
insert into auth.users(id,email) select u,'qa-'||u||'@example.invalid' from fixtures union all select u2,'qa-'||u2||'@example.invalid' from fixtures union all select merchant,'qa-'||merchant||'@example.invalid' from fixtures union all select foreign_merchant,'qa-'||foreign_merchant||'@example.invalid' from fixtures;
insert into public.profiles(user_id,display_name,live_enabled) select u,'QA customer',true from fixtures union all select u2,'QA other',false from fixtures;
insert into public.businesses(id,slug,name,category_id,status,enrollment_status,booking_enabled,timezone,reward_rate) select b,'qa-'||b,'QA promotion business',(select id from public.categories limit 1),'published','active',true,'America/Mazatlan',.1 from fixtures;
insert into public.business_members(business_id,user_id,role) select b,merchant,'owner' from fixtures;
insert into public.services(id,business_id,name,name_es,name_en,duration_minutes,price_mxn) select s,b,'QA Service','Servicio QA','QA Service',30,1000 from fixtures;
insert into public.collaborators(id,business_id,name,active) select c,b,'QA collaborator',true from fixtures;
insert into public.business_opening_hours(business_id,weekday,opens_at,closes_at) select b,extract(dow from (now() at time zone 'America/Mazatlan')::date+1),'12:00','15:00' from fixtures;
insert into public.collaborator_services(business_id,collaborator_id,service_id) select b,c,s from fixtures;
insert into public.availability(business_id,collaborator_id,weekday,opens_at,closes_at) select b,c,extract(dow from (now() at time zone 'America/Mazatlan')::date+1),'12:00','15:00' from fixtures;
insert into public.promotions(id,business_id,service_id,title,title_es,title_en,description_es,description_en,special_price_mxn,placement,status,starts_at,ends_at) select p,b,s,'QA Promo','QA Promo','QA Promo','Prueba','Test',800,'live','published',now()-interval '1 hour',now()+interval '7 days' from fixtures;
insert into public.promotions(id,business_id,service_id,title,title_es,title_en,description_es,description_en,special_price_mxn,placement,status,starts_at,ends_at) select pfuture,b,s,'Scheduled QA','Scheduled QA','Scheduled QA','Prueba','Test',800,'live','published',now()+interval '1 day',now()+interval '7 days' from fixtures;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures; t record; booking public.visits; begin select * into f from fixtures;
 if (select count(*) from public.promotions where id=f.pfuture)<>0 then raise exception 'Scheduled promotion leaked'; end if;
 perform public.record_promotion_click(f.p,f.click,'capsule');perform public.record_promotion_click(f.p,f.click,'capsule');
 if (select count(*) from public.promotion_clicks where id=f.click)<>1 then raise exception 'Duplicate click';end if;
 select * into t from public.promotion_slots(f.p,(now() at time zone 'America/Mazatlan')::date+1) limit 1;
 if t.starts_at is null then raise exception 'No slots';end if;
 booking=public.book_promotion(f.p,f.click,t.collaborator_id,t.starts_at);
 if booking.booked_price_mxn<>800 or booking.promotion_id<>f.p or booking.customer_id<>f.u then raise exception 'Wrong booking';end if;
 if (public.book_promotion(f.p,f.click,t.collaborator_id,t.starts_at)).id<>booking.id then raise exception 'Duplicate booking';end if;
 update fixtures set v=booking.id,start_at=t.starts_at;
 begin insert into public.promotion_clicks(id,promotion_id,business_id,customer_id,service_id,source) values(gen_random_uuid(),f.p,f.b,f.u2,f.s,'capsule'); raise exception 'Client forged analytics';exception when insufficient_privilege then null;end;
 if (select count(*) from public.promotion_metrics)<>0 then raise exception 'Customer saw merchant KPIs';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures;begin select * into f from fixtures;
 begin perform public.record_promotion_click(f.p,f.click2,'capsule');raise exception 'Live opt-out bypassed';exception when raise_exception then if sqlerrm='Live opt-out bypassed' then raise;end if;end;
 if (select count(*) from public.promotion_clicks where id=f.click)<>0 then raise exception 'Foreign customer click leaked';end if;
end $$;
reset role;
update public.profiles set live_enabled=true where user_id=(select u2 from fixtures);
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures;begin select * into f from fixtures;
 perform public.record_promotion_click(f.p,f.click2,'live_list');
 begin perform public.book_promotion(f.p,f.click2,f.c,f.start_at);raise exception 'Double booking accepted';exception when raise_exception then if sqlerrm='Double booking accepted' then raise;end if;end;
 begin perform public.book_promotion(f.p,f.click,f.c,f.start_at);raise exception 'Foreign attribution accepted';exception when raise_exception then if sqlerrm='Foreign attribution accepted' then raise;end if;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',merchant,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures; m record;begin select * into f from fixtures;select * into m from public.promotion_metrics where promotion_id=f.p;
 if m.clicks<>2 or m.unique_customers<>2 or m.bookings<>1 or m.completed<>0 or m.new_acquisitions<>0 then raise exception 'Bad initial KPIs %',row_to_json(m);end if;
 begin perform public.complete_promotion_visit(f.v,800);raise exception 'Future service completed';exception when raise_exception then if sqlerrm='Future service completed' then raise;end if;end;
end $$;
reset role;
update public.visits set starts_at=now()-interval '2 hours',ends_at=now()-interval '90 minutes' where id=(select v from fixtures);
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',merchant,'role','authenticated')::text,true) from fixtures;
select public.complete_promotion_visit(v,800) from fixtures;
select public.complete_promotion_visit(v,800) from fixtures;
do $$declare f fixtures;m record;begin select * into f from fixtures;select * into m from public.promotion_metrics where promotion_id=f.p;
 if m.completed<>1 or m.new_acquisitions<>1 or m.revenue_mxn<>800 then raise exception 'Bad realized KPIs %',row_to_json(m);end if;
 if (select count(*) from public.reward_ledger where visit_id=f.v)<>1 then raise exception 'Duplicate rewards';end if;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',foreign_merchant,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures;begin select * into f from fixtures;
 if (select count(*) from public.promotion_metrics)<>0 then raise exception 'Other merchant KPI leaked';end if;
 begin perform public.complete_promotion_visit(f.v,800);raise exception 'Other merchant completed service';exception when raise_exception then if sqlerrm='Other merchant completed service' then raise;end if;end;
end $$;
reset role;
-- Same customer returns via the same promotion: acquisition must remain one.
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures; t record; booking public.visits;begin select * into f from fixtures;select * into t from public.promotion_slots(f.p,(now() at time zone 'America/Mazatlan')::date+1) limit 1;
 booking=public.book_promotion(f.p,public.record_promotion_click(f.p,gen_random_uuid(),'service_cta'),t.collaborator_id,t.starts_at);update fixtures set v=booking.id;end $$;
reset role;
update public.visits set starts_at=now()-interval '1 hour',ends_at=now()-interval '30 minutes' where id=(select v from fixtures);
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',merchant,'role','authenticated')::text,true) from fixtures;
select public.complete_promotion_visit(v,800) from fixtures;
do $$declare f fixtures;m record;begin select * into f from fixtures;select * into m from public.promotion_metrics where promotion_id=f.p;if m.completed<>2 or m.new_acquisitions<>1 or m.revenue_mxn<>1600 then raise exception 'Returning customer counted as new %',row_to_json(m);end if;end $$;
reset role;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',foreign_merchant,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures;begin select * into f from fixtures;
 begin insert into public.promotions(business_id,title,ends_at) values(f.b,'Forbidden',now()+interval '1 day');raise exception 'Other merchant created promotion';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',merchant,'role','authenticated')::text,true) from fixtures;
do $$declare f fixtures;draft uuid;begin select * into f from fixtures;
 insert into public.promotions(business_id,title,ends_at,placement) values(f.b,'Draft QA',now()+interval '2 days','live') returning id into draft;
 begin update public.promotions set status='published' where id=draft;raise exception 'Incomplete activation allowed';exception when raise_exception then if sqlerrm='Incomplete activation allowed' then raise;end if;end;
 update public.promotions set service_id=f.s,title_es='Programada',title_en='Scheduled',description_es='Prueba',description_en='Test',special_price_mxn=750,status='published',starts_at=now()+interval '1 day' where id=draft;
 if not found then raise exception 'Manager update failed';end if;
 update public.promotions set status='hidden' where id=draft;
 if (select status from public.promotions where id=draft)<>'hidden' then raise exception 'Manual hiding failed';end if;
 begin update public.promotions set images='[{"url":"https://example.invalid/1"},{"url":"https://example.invalid/2"},{"url":"https://example.invalid/3"},{"url":"https://example.invalid/4"},{"url":"https://example.invalid/5"},{"url":"https://example.invalid/6"}]' where id=draft;raise exception 'Six photos accepted';exception when check_violation then null;end;
 update public.promotions set status='published',starts_at=now()-interval '1 hour' where id=draft;
 begin update public.promotions set special_price_mxn=1100 where id=draft;raise exception 'Invalid special price accepted';exception when raise_exception then if sqlerrm='Invalid special price accepted' then raise;end if;end;
end $$;
reset role;
rollback;
select 'PASS: merchant CRUD and gallery limits, scheduling, click/booking idempotency, opt-out, slot conflicts, attribution ownership, tenant isolation, completed revenue, first customer acquisition and repeat customer' result;
